-- Idempotent FAnn catalog enrichment from public product detail pages.
-- Adds 30 current variants and enriches 23 existing seed products found in the current catalog.
-- Source snapshot checked on 2026-09-21; profile probabilities are retained only for future upsell use.

SET NAMES utf8mb4;
START TRANSACTION;

UPDATE `product` SET
  `description` = 'Giorgio Armani představuje vůni ACQUA DI GIÒ EAU DE TOILETTE, jež v sobě zachycuje esenci Středomoří. Vůně se otevírá mořskými a bergamotovými nóty, které vytvářejí její ikonickou svěžest.',
  `price` = 2070.00,
  `variant` = 'toaletní voda 30 ml',
  `data` = JSON_MERGE_PATCH(COALESCE(`data`, JSON_OBJECT()), CAST('{"catalog_source":{"shop":"FAnn parfumerie","url":"https://www.fann.cz/produkty/acqua-di-gio-eau-de-toilette/10602/20536","product_id":10602,"variant_id":20536,"ean":"3614273955560","checked_at":"2026-09-21"},"brand":"Armani","variant_label":"toaletní voda 30 ml","availability_at_check":"InStock","selection_attributes":{"category":["vůně"],"product_type":["toaletní voda"],"target_audience":["muži"],"fragrance_character":["svěží","citrusová","květinová","dřevitá","pižmová"],"fragrance_notes":[],"concentration":["toaletní voda"]},"diagnostic_questions":["Pro koho vůni vybíráte a jaké vůně běžně používá?","Má být spíše svěží, květinová, sladká, dřevitá, nebo kořeněná?","Je vůně na každý den, večer, konkrétní období, nebo jako dárek?","Jak výraznou vůni a jaký rozpočet preferujete?"]}' AS JSON)),
  `published` = 1,
  `deleted` = 0
WHERE `franchise_code` = 'fun' AND `sku` = 'FUN-P001';

UPDATE `product` SET
  `description` = 'Intenzivní interpretace ikonické vůně Acqua di Giò se vrací k základnímu elementu řady: k hlubinám moře. Vůně kombinuje zelenou mandarinku, bergamot, mořské nóty a dřevité akordy.',
  `price` = 4770.00,
  `variant` = 'parfémová voda 125 ml',
  `data` = JSON_MERGE_PATCH(COALESCE(`data`, JSON_OBJECT()), CAST('{"catalog_source":{"shop":"FAnn parfumerie","url":"https://www.fann.cz/produkty/acqua-di-gio-profondo/7319/13969","product_id":7319,"variant_id":13969,"ean":"3614272865235","checked_at":"2026-09-21"},"brand":"Armani","variant_label":"parfémová voda 125 ml","availability_at_check":"InStock","selection_attributes":{"category":["vůně"],"product_type":["parfémová voda"],"fragrance_character":["citrusová","dřevitá","pižmová","intenzivní"],"fragrance_notes":["zelená mandarinkou a bergamotem","ozmarýn, levandule a cypriš","dřevité nóty pačuli, pižma a mořských nót"],"concentration":["parfémová voda"]},"diagnostic_questions":["Pro koho vůni vybíráte a jaké vůně běžně používá?","Má být spíše svěží, květinová, sladká, dřevitá, nebo kořeněná?","Je vůně na každý den, večer, konkrétní období, nebo jako dárek?","Jak výraznou vůni a jaký rozpočet preferujete?"]}' AS JSON)),
  `published` = 1,
  `deleted` = 0
WHERE `franchise_code` = 'fun' AND `sku` = 'FUN-P002';

UPDATE `product` SET
  `description` = 'Giorgio Armani představuje vůni ACQUA DI GIÒ PARFUM. Objevte jedinečnou vonnou kompozici, která v sobě spojuje svěžest vody s hřejivostí dřeva a intenzitou aromat, a to vše ve flakonu, který se vyznačuje nejen výrazným designem, ale také vysoce kvalitním zpracováním pro dlouhou životnost.',
  `price` = 2690.00,
  `variant` = 'parfém 30 ml',
  `data` = JSON_MERGE_PATCH(COALESCE(`data`, JSON_OBJECT()), CAST('{"catalog_source":{"shop":"FAnn parfumerie","url":"https://www.fann.cz/produkty/acqua-di-gio-parfum/10604/20541","product_id":10604,"variant_id":20541,"ean":"3614273954181","checked_at":"2026-09-21"},"brand":"Armani","variant_label":"parfém 30 ml","availability_at_check":"InStock","selection_attributes":{"category":["vůně"],"product_type":["parfém"],"target_audience":["muži"],"fragrance_character":["svěží","citrusová","dřevitá","kořeněná","intenzivní"],"occasion":["večer"],"fragrance_notes":[],"concentration":["toaletní voda"]},"diagnostic_questions":["Pro koho vůni vybíráte a jaké vůně běžně používá?","Má být spíše svěží, květinová, sladká, dřevitá, nebo kořeněná?","Je vůně na každý den, večer, konkrétní období, nebo jako dárek?","Jak výraznou vůni a jaký rozpočet preferujete?"]}' AS JSON)),
  `published` = 1,
  `deleted` = 0
WHERE `franchise_code` = 'fun' AND `sku` = 'FUN-P003';

UPDATE `product` SET
  `description` = 'Vůni dodávají intenzitu počáteční kontrastní svěží a kořenité tóny za pomoci růžového pepře. Získá si vás díky svému unikátnímu akordu kaštanů obalených v cukru.',
  `price` = 2310.00,
  `variant` = 'parfémová voda 30 ml',
  `data` = JSON_MERGE_PATCH(COALESCE(`data`, JSON_OBJECT()), CAST('{"catalog_source":{"shop":"FAnn parfumerie","url":"https://www.fann.cz/produkty/stronger-with-you-intensely/6507/12329","product_id":6507,"variant_id":12329,"ean":"3614272225695","checked_at":"2026-09-21"},"brand":"Armani","variant_label":"parfémová voda 30 ml","availability_at_check":"InStock","selection_attributes":{"category":["vůně"],"product_type":["parfémová voda"],"fragrance_character":["svěží","kořeněná","ambrová","intenzivní"],"fragrance_notes":["Esence z růžového pepře, absolut z fialek, esence z jalovce","Levandule, šalvěj, kosatec, skořice","Esence z vanilky, kaštanový akord, absolut z tonka fazolí"],"concentration":["parfémová voda"]},"diagnostic_questions":["Pro koho vůni vybíráte a jaké vůně běžně používá?","Má být spíše svěží, květinová, sladká, dřevitá, nebo kořeněná?","Je vůně na každý den, večer, konkrétní období, nebo jako dárek?","Jak výraznou vůni a jaký rozpočet preferujete?"]}' AS JSON)),
  `published` = 1,
  `deleted` = 0
WHERE `franchise_code` = 'fun' AND `sku` = 'FUN-P004';

UPDATE `product` SET
  `description` = 'Ikonická vůně vstupuje do nové éry Giorgio Armani představuje Armani Code EAU DE TOILETTE. Objevte nadčasovou vonnou kompozici v novém výrazném flakonu, který má nápaditý design a je vytvořen tak, aby vydržel.',
  `price` = 2690.00,
  `variant` = 'toaletní voda 50 ml',
  `data` = JSON_MERGE_PATCH(COALESCE(`data`, JSON_OBJECT()), CAST('{"catalog_source":{"shop":"FAnn parfumerie","url":"https://www.fann.cz/produkty/armani-code/9614/18334","product_id":9614,"variant_id":18334,"ean":"3614273636582","checked_at":"2026-09-21"},"brand":"Armani","variant_label":"toaletní voda 50 ml","availability_at_check":"InStock","selection_attributes":{"category":["vůně"],"product_type":["toaletní voda"],"target_audience":["muži","citlivá pleť nebo oči"],"fragrance_character":["citrusová","dřevitá","ambrová","intenzivní"],"fragrance_notes":["citrusové tóny, zelená mandarinka z italské Kalábrie","levandule z Provence","brazilské tonka fazole a cedrové dřevo z Virginie"],"concentration":["toaletní voda"]},"diagnostic_questions":["Pro koho vůni vybíráte a jaké vůně běžně používá?","Má být spíše svěží, květinová, sladká, dřevitá, nebo kořeněná?","Je vůně na každý den, večer, konkrétní období, nebo jako dárek?","Jak výraznou vůni a jaký rozpočet preferujete?"]}' AS JSON)),
  `published` = 1,
  `deleted` = 0
WHERE `franchise_code` = 'fun' AND `sku` = 'FUN-P005';

UPDATE `product` SET
  `description` = 'Jeden z absolutních bestsellerů mezi moderními pánskými vůněmi, který vládne nezaměnitelně svěžími a stylovými tóny mísícími klasiku s geniálním nápadem. Je určena modernímu úspěšnému muži, který žije ve světě, kde nic není nemožné.',
  `price` = 2060.00,
  `variant` = 'toaletní voda 30 ml',
  `data` = JSON_MERGE_PATCH(COALESCE(`data`, JSON_OBJECT()), CAST('{"catalog_source":{"shop":"FAnn parfumerie","url":"https://www.fann.cz/produkty/bottled/184/18191","product_id":184,"variant_id":18191,"ean":"737052351001","checked_at":"2026-09-21"},"brand":"Hugo Boss","variant_label":"toaletní voda 30 ml","availability_at_check":"InStock","selection_attributes":{"category":["vůně"],"product_type":["toaletní voda"],"target_audience":["muži"],"fragrance_character":["svěží","ovocná","ambrová"],"fragrance_notes":["červené jablko, skořice","muškát, zelené tóny","olivové dřevo, ambra"],"concentration":["toaletní voda"]},"diagnostic_questions":["Pro koho vůni vybíráte a jaké vůně běžně používá?","Má být spíše svěží, květinová, sladká, dřevitá, nebo kořeněná?","Je vůně na každý den, večer, konkrétní období, nebo jako dárek?","Jak výraznou vůni a jaký rozpočet preferujete?"]}' AS JSON)),
  `published` = 1,
  `deleted` = 0
WHERE `franchise_code` = 'fun' AND `sku` = 'FUN-P006';

UPDATE `product` SET
  `description` = 'BOSS Parfums věří ve svádění, které útočí na mysl a zanechává trvalou stopu. Vůně, která vytvoří tento efekt, je naprosto jedinečná.',
  `price` = 2850.00,
  `variant` = 'toaletní voda 50 ml',
  `data` = JSON_MERGE_PATCH(COALESCE(`data`, JSON_OBJECT()), CAST('{"catalog_source":{"shop":"FAnn parfumerie","url":"https://www.fann.cz/produkty/the-scent/3438/6483","product_id":3438,"variant_id":6483,"ean":"737052972268","checked_at":"2026-09-21"},"brand":"Hugo Boss","variant_label":"toaletní voda 50 ml","availability_at_check":"InStock","selection_attributes":{"category":["vůně"],"product_type":["toaletní voda"],"fragrance_character":["citrusová","ovocná"],"fragrance_notes":["zázvor, bergamot, šalvěj, cypřiš","maninka, levandule, fialky, kadidlo","tóny kůže"],"concentration":["toaletní voda"]},"diagnostic_questions":["Pro koho vůni vybíráte a jaké vůně běžně používá?","Má být spíše svěží, květinová, sladká, dřevitá, nebo kořeněná?","Je vůně na každý den, večer, konkrétní období, nebo jako dárek?","Jak výraznou vůni a jaký rozpočet preferujete?"]}' AS JSON)),
  `published` = 1,
  `deleted` = 0
WHERE `franchise_code` = 'fun' AND `sku` = 'FUN-P007';

UPDATE `product` SET
  `description` = 'Láska, vášeň, krása a touha – to jsou klíčové prvky pánské vůně Versace. Dokonalost mužského těla propojená s odkazy k antické mytologii a klasickému sochařství reprezentují charakteristické prvky stylu Versace už od jeho samotných počátků.',
  `price` = 1990.00,
  `variant` = 'toaletní voda 30 ml',
  `data` = JSON_MERGE_PATCH(COALESCE(`data`, JSON_OBJECT()), CAST('{"catalog_source":{"shop":"FAnn parfumerie","url":"https://www.fann.cz/produkty/eros/399/1616","product_id":399,"variant_id":1616,"ean":"8011003809196","checked_at":"2026-09-21"},"brand":"Versace","variant_label":"toaletní voda 30 ml","availability_at_check":"InStock","selection_attributes":{"category":["vůně"],"product_type":["toaletní voda"],"target_audience":["muži"],"fragrance_character":["citrusová","ovocná","dřevitá","sladká","ambrová"],"fragrance_notes":["máta, citron, jablko","ambra, pelargónie, vanilka, fazole tonka","dubový mech, vetiver, cedr"],"concentration":["toaletní voda"]},"diagnostic_questions":["Pro koho vůni vybíráte a jaké vůně běžně používá?","Má být spíše svěží, květinová, sladká, dřevitá, nebo kořeněná?","Je vůně na každý den, večer, konkrétní období, nebo jako dárek?","Jak výraznou vůni a jaký rozpočet preferujete?"]}' AS JSON)),
  `published` = 1,
  `deleted` = 0
WHERE `franchise_code` = 'fun' AND `sku` = 'FUN-P008';

UPDATE `product` SET
  `description` = '1 MILLION - vůně bořící hranice, spojující drzost a vtip, připomínající každou mužskou touhu a přání. Zlatý ingot, který se stal nejprodávanějším na každém trhu, na který vstoupil.',
  `price` = 1870.00,
  `variant` = 'toaletní voda 30 ml',
  `data` = JSON_MERGE_PATCH(COALESCE(`data`, JSON_OBJECT()), CAST('{"catalog_source":{"shop":"FAnn parfumerie","url":"https://www.fann.cz/produkty/1million/317/24143","product_id":317,"variant_id":24143,"ean":"3349668677405","checked_at":"2026-09-21"},"brand":"Rabanne","variant_label":"toaletní voda 30 ml","availability_at_check":"InStock","selection_attributes":{"category":["vůně"],"product_type":["toaletní voda"],"target_audience":["muži"],"fragrance_character":["citrusová","květinová","ambrová"],"fragrance_notes":["grapefruit, máta, pomeranč","růže, skořice","bílé dřeviny, ambra, pačuli"],"concentration":["toaletní voda"]},"diagnostic_questions":["Pro koho vůni vybíráte a jaké vůně běžně používá?","Má být spíše svěží, květinová, sladká, dřevitá, nebo kořeněná?","Je vůně na každý den, večer, konkrétní období, nebo jako dárek?","Jak výraznou vůni a jaký rozpočet preferujete?"]}' AS JSON)),
  `published` = 1,
  `deleted` = 0
WHERE `franchise_code` = 'fun' AND `sku` = 'FUN-P009';

UPDATE `product` SET
  `description` = 'Objevme spolu dobrodružství evropských průkopníků, kteří kdysi procestovali svět. Propracovaný design flakónu - nejlepší kvalita díky evropské zručnosti.',
  `price` = 1520.00,
  `variant` = 'parfémová voda 30 ml',
  `data` = JSON_MERGE_PATCH(COALESCE(`data`, JSON_OBJECT()), CAST('{"catalog_source":{"shop":"FAnn parfumerie","url":"https://www.fann.cz/produkty/explorer/6515/12346","product_id":6515,"variant_id":12346,"ean":"3386460101059","checked_at":"2026-09-21"},"brand":"Montblanc","variant_label":"parfémová voda 30 ml","availability_at_check":"InStock","selection_attributes":{"category":["vůně"],"product_type":["parfémová voda"],"target_audience":["muži"],"finish_and_effect":["přirozený"],"fragrance_character":["svěží","citrusová","dřevitá"],"fragrance_notes":["vetiver, kůže, santalové dřevo","bergamot, hřebíčkovec, šalvěj","pačuli, ambrofix, akigalawood"],"concentration":["parfémová voda"]},"diagnostic_questions":["Pro koho vůni vybíráte a jaké vůně běžně používá?","Má být spíše svěží, květinová, sladká, dřevitá, nebo kořeněná?","Je vůně na každý den, večer, konkrétní období, nebo jako dárek?","Jak výraznou vůni a jaký rozpočet preferujete?"]}' AS JSON)),
  `published` = 1,
  `deleted` = 0
WHERE `franchise_code` = 'fun' AND `sku` = 'FUN-P010';

UPDATE `product` SET
  `description` = 'My Way je vůní objevování. Je vůní pro ženu, která je sama sebou, je připravena rozšiřovat své obzory a získávat nové zkušenosti, které ji neustále posouvají vpřed.',
  `price` = 2380.00,
  `variant` = 'parfémová voda 30 ml',
  `data` = JSON_MERGE_PATCH(COALESCE(`data`, JSON_OBJECT()), CAST('{"catalog_source":{"shop":"FAnn parfumerie","url":"https://www.fann.cz/produkty/my-way/7596/14543","product_id":7596,"variant_id":14543,"ean":"3614272907652","checked_at":"2026-09-21"},"brand":"Armani","variant_label":"parfémová voda 30 ml","availability_at_check":"InStock","selection_attributes":{"category":["vůně"],"product_type":["parfémová voda"],"target_audience":["ženy"],"fragrance_character":["citrusová","květinová","dřevitá","sladká","pižmová","intenzivní"],"fragrance_notes":["cedrové dřevo, vanilka","tuberóza, jasmín","bergamot, pomerančový květ"],"concentration":["parfémová voda"]},"diagnostic_questions":["Pro koho vůni vybíráte a jaké vůně běžně používá?","Má být spíše svěží, květinová, sladká, dřevitá, nebo kořeněná?","Je vůně na každý den, večer, konkrétní období, nebo jako dárek?","Jak výraznou vůni a jaký rozpočet preferujete?"]}' AS JSON)),
  `published` = 1,
  `deleted` = 0
WHERE `franchise_code` = 'fun' AND `sku` = 'FUN-P011';

UPDATE `product` SET
  `description` = 'Luxusní dámská vůně Giorgio Armani Si vzdává hold moderní ženskosti, přirozené kráse a pocitu svobody. Žena Giorgio Armani je za každé situace šarmantní, silná a nezávislá.',
  `price` = 2380.00,
  `variant` = 'parfémová voda 30 ml',
  `data` = JSON_MERGE_PATCH(COALESCE(`data`, JSON_OBJECT()), CAST('{"catalog_source":{"shop":"FAnn parfumerie","url":"https://www.fann.cz/produkty/si/465/612","product_id":465,"variant_id":612,"ean":"3605521816511","checked_at":"2026-09-21"},"brand":"Armani","variant_label":"parfémová voda 30 ml","availability_at_check":"InStock","selection_attributes":{"category":["vůně"],"product_type":["parfémová voda"],"target_audience":["ženy","citlivá pleť nebo oči"],"finish_and_effect":["přirozený"],"fragrance_character":["květinová","sladká"],"fragrance_notes":["cassis","růže, frézie","pačuli, vanilka, dřevo, ambroxan"],"concentration":["parfémová voda"]},"diagnostic_questions":["Pro koho vůni vybíráte a jaké vůně běžně používá?","Má být spíše svěží, květinová, sladká, dřevitá, nebo kořeněná?","Je vůně na každý den, večer, konkrétní období, nebo jako dárek?","Jak výraznou vůni a jaký rozpočet preferujete?"]}' AS JSON)),
  `published` = 1,
  `deleted` = 0
WHERE `franchise_code` = 'fun' AND `sku` = 'FUN-P012';

UPDATE `product` SET
  `description` = 'Nová působivá verze nenapodobitelné řady vůní Armani, Sì Passione přidává ženské olfaktorické osobnosti Giorgio Armani novou dimenzi. Slovy slavného návrháře jde o „neodolatelnou kombinaci půvabu, síly a nezávislosti duše." Sì Passione kombinuje intenzivní vanilku s květy růže, otočníku a jasmínu a vytváří smyslnou, ovocnou a květinovou vůni, od níž se odráží něha a zároveň síla ženskosti.',
  `price` = 2380.00,
  `variant` = 'parfémová voda 30 ml',
  `data` = JSON_MERGE_PATCH(COALESCE(`data`, JSON_OBJECT()), CAST('{"catalog_source":{"shop":"FAnn parfumerie","url":"https://www.fann.cz/produkty/si-passione/5414/9960","product_id":5414,"variant_id":9960,"ean":"3614271994721","checked_at":"2026-09-21"},"brand":"Armani","variant_label":"parfémová voda 30 ml","availability_at_check":"InStock","selection_attributes":{"category":["vůně"],"product_type":["parfémová voda"],"target_audience":["ženy"],"fragrance_character":["květinová","ovocná","dřevitá","kořeněná","ambrová","intenzivní"],"fragrance_notes":["růžový pepř","hruška","růže"],"concentration":["parfémová voda"]},"diagnostic_questions":["Pro koho vůni vybíráte a jaké vůně běžně používá?","Má být spíše svěží, květinová, sladká, dřevitá, nebo kořeněná?","Je vůně na každý den, večer, konkrétní období, nebo jako dárek?","Jak výraznou vůni a jaký rozpočet preferujete?"]}' AS JSON)),
  `published` = 1,
  `deleted` = 0
WHERE `franchise_code` = 'fun' AND `sku` = 'FUN-P013';

UPDATE `product` SET
  `description` = 'Ikonická vůně a bestseller posledních let ve světě vůní je oslavou ženy a přírody. Sladká, ale osvěžující vůně, nevtíravá, přitom výrazná, uklidňující, ale vyzývavá.',
  `price` = 2070.00,
  `variant` = 'parfémová voda 30 ml',
  `data` = JSON_MERGE_PATCH(COALESCE(`data`, JSON_OBJECT()), CAST('{"catalog_source":{"shop":"FAnn parfumerie","url":"https://www.fann.cz/produkty/acqua-di-gioia/2566/7132","product_id":2566,"variant_id":7132,"ean":"3605521172648","checked_at":"2026-09-21"},"brand":"Armani","variant_label":"parfémová voda 30 ml","availability_at_check":"InStock","selection_attributes":{"category":["vůně"],"product_type":["parfémová voda"],"target_audience":["ženy"],"fragrance_character":["svěží","citrusová","květinová","dřevitá","sladká","kořeněná","intenzivní"],"occasion":["každodenní použití"],"fragrance_notes":["máta, citron amalfi","růžový pepř, pivoňka, jasmín","cedr, cukr, francouzské labdanum"],"concentration":["parfémová voda"]},"diagnostic_questions":["Pro koho vůni vybíráte a jaké vůně běžně používá?","Má být spíše svěží, květinová, sladká, dřevitá, nebo kořeněná?","Je vůně na každý den, večer, konkrétní období, nebo jako dárek?","Jak výraznou vůni a jaký rozpočet preferujete?"]}' AS JSON)),
  `published` = 1,
  `deleted` = 0
WHERE `franchise_code` = 'fun' AND `sku` = 'FUN-P014';

UPDATE `product` SET
  `description` = 'LIBRE, nová dámská vůně Yves Saint Laurent. Vůně silné, odvážné a svobodné ženy.Žijte život podle vlastních pravidel.Buďte sama sebou.Bez kompromisů.',
  `price` = 2590.00,
  `variant` = 'parfémová voda 30 ml',
  `data` = JSON_MERGE_PATCH(COALESCE(`data`, JSON_OBJECT()), CAST('{"catalog_source":{"shop":"FAnn parfumerie","url":"https://www.fann.cz/produkty/libre/6936/13363","product_id":6936,"variant_id":13363,"ean":"3614272648401","checked_at":"2026-09-21"},"brand":"Yves Saint Laurent","variant_label":"parfémová voda 30 ml","availability_at_check":"InStock","selection_attributes":{"category":["vůně"],"product_type":["parfémová voda"],"target_audience":["ženy"],"fragrance_character":["svěží","citrusová","květinová","ovocná","dřevitá","sladká","ambrová"],"fragrance_notes":["Mandarinka, lavandin, černý rybíz","Levandule, květ pomerančovníku, jasmín","Vanilka, cedrové dřevo, ambra"],"concentration":["parfémová voda"]},"diagnostic_questions":["Pro koho vůni vybíráte a jaké vůně běžně používá?","Má být spíše svěží, květinová, sladká, dřevitá, nebo kořeněná?","Je vůně na každý den, večer, konkrétní období, nebo jako dárek?","Jak výraznou vůni a jaký rozpočet preferujete?"]}' AS JSON)),
  `published` = 1,
  `deleted` = 0
WHERE `franchise_code` = 'fun' AND `sku` = 'FUN-P015';

UPDATE `product` SET
  `description` = 'Vůně Black Opium vás překvapí podmanivou kombinací bílých květů s hořkým akordem kávového zrna a jemné vanilky.',
  `price` = 2390.00,
  `variant` = 'parfémová voda 30 ml',
  `data` = JSON_MERGE_PATCH(COALESCE(`data`, JSON_OBJECT()), CAST('{"catalog_source":{"shop":"FAnn parfumerie","url":"https://www.fann.cz/produkty/black-opium/3019/5641","product_id":3019,"variant_id":5641,"ean":"3365440787858","checked_at":"2026-09-21"},"brand":"Yves Saint Laurent","variant_label":"parfémová voda 30 ml","availability_at_check":"InStock","selection_attributes":{"category":["vůně"],"product_type":["parfémová voda"],"fragrance_character":["citrusová","květinová","kořeněná"],"fragrance_notes":["esence růžového pepře, esence mandarinky, hruškový akord","absolut pomerančových květů, absolut sambackého jasmínu","kávový akord, absolut vanilky"],"concentration":["parfémová voda"]},"diagnostic_questions":["Pro koho vůni vybíráte a jaké vůně běžně používá?","Má být spíše svěží, květinová, sladká, dřevitá, nebo kořeněná?","Je vůně na každý den, večer, konkrétní období, nebo jako dárek?","Jak výraznou vůni a jaký rozpočet preferujete?"]}' AS JSON)),
  `published` = 1,
  `deleted` = 0
WHERE `franchise_code` = 'fun' AND `sku` = 'FUN-P016';

UPDATE `product` SET
  `description` = 'IKONICKÁ VŮNĚ ŠTĚSTÍUdělejte si dnešní den krásným, znovu a znovu, doprovázený ikonickou vůní od Lancôme.Květinová gurmánská vůně uzavřená v křišťálovém úsměvu. Univerzální vyznání štěstí a radostné ženskosti.',
  `price` = 2340.00,
  `variant` = 'parfémová voda 30 ml',
  `data` = JSON_MERGE_PATCH(COALESCE(`data`, JSON_OBJECT()), CAST('{"catalog_source":{"shop":"FAnn parfumerie","url":"https://www.fann.cz/produkty/la-vie-est-belle/2568/1082","product_id":2568,"variant_id":1082,"ean":"3605532612690","checked_at":"2026-09-21"},"brand":"Lancôme","variant_label":"parfémová voda 30 ml","availability_at_check":"InStock","selection_attributes":{"category":["vůně"],"product_type":["parfémová voda"],"target_audience":["ženy"],"fragrance_character":["květinová","ovocná","gurmánská","sladká"],"fragrance_notes":["hruška, černý rybíz","jasmín, květ pomerančovníku, kosatec","pačuli, vanilka, ořechy, tonka fazole"],"concentration":["parfémová voda"]},"diagnostic_questions":["Pro koho vůni vybíráte a jaké vůně běžně používá?","Má být spíše svěží, květinová, sladká, dřevitá, nebo kořeněná?","Je vůně na každý den, večer, konkrétní období, nebo jako dárek?","Jak výraznou vůni a jaký rozpočet preferujete?"]}' AS JSON)),
  `published` = 1,
  `deleted` = 0
WHERE `franchise_code` = 'fun' AND `sku` = 'FUN-P017';

UPDATE `product` SET
  `description` = 'Pro všechny ženy, které sní ve velkém. Pro novou generaci žen.',
  `price` = 1980.00,
  `variant` = 'parfémová voda 25 ml',
  `data` = JSON_MERGE_PATCH(COALESCE(`data`, JSON_OBJECT()), CAST('{"catalog_source":{"shop":"FAnn parfumerie","url":"https://www.fann.cz/produkty/idole/6909/18596","product_id":6909,"variant_id":18596,"ean":"3614272639638","checked_at":"2026-09-21"},"brand":"Lancôme","variant_label":"parfémová voda 25 ml","availability_at_check":"InStock","selection_attributes":{"category":["vůně"],"product_type":["parfémová voda"],"fragrance_character":["citrusová","květinová","dřevitá"],"fragrance_notes":["esence bergamotu","esence růže, absolut růže, růžová voda, nádech a absolut jasmínu","pačuli, esence cedru, extrakt vanilky"],"concentration":["parfémová voda"]},"diagnostic_questions":["Pro koho vůni vybíráte a jaké vůně běžně používá?","Má být spíše svěží, květinová, sladká, dřevitá, nebo kořeněná?","Je vůně na každý den, večer, konkrétní období, nebo jako dárek?","Jak výraznou vůni a jaký rozpočet preferujete?"]}' AS JSON)),
  `published` = 1,
  `deleted` = 0
WHERE `franchise_code` = 'fun' AND `sku` = 'FUN-P018';

UPDATE `product` SET
  `description` = 'Více než vůně – je to doslova životní postoj. DKNY Be Delicious zachycuje dobrodružnou duši New Yorku.',
  `price` = 1780.00,
  `variant` = 'parfémová voda 30 ml',
  `data` = JSON_MERGE_PATCH(COALESCE(`data`, JSON_OBJECT()), CAST('{"catalog_source":{"shop":"FAnn parfumerie","url":"https://www.fann.cz/produkty/be-delicious/111/5378","product_id":111,"variant_id":5378,"ean":"085715004192","checked_at":"2026-09-21"},"brand":"DKNY","variant_label":"parfémová voda 30 ml","availability_at_check":"InStock","selection_attributes":{"category":["vůně"],"product_type":["parfémová voda"],"fragrance_character":["svěží","květinová","ovocná","dřevitá","sladká","ambrová"],"fragrance_notes":["grapefruit, okurka, jablko, magnólie","tuberóza, fialka, růže, konvalinka","květinové tóny, dřevo, santalové dřevo, ambra"],"concentration":["parfémová voda"]},"diagnostic_questions":["Pro koho vůni vybíráte a jaké vůně běžně používá?","Má být spíše svěží, květinová, sladká, dřevitá, nebo kořeněná?","Je vůně na každý den, večer, konkrétní období, nebo jako dárek?","Jak výraznou vůni a jaký rozpočet preferujete?"]}' AS JSON)),
  `published` = 1,
  `deleted` = 0
WHERE `franchise_code` = 'fun' AND `sku` = 'FUN-P019';

UPDATE `product` SET
  `description` = 'Lady Million je svěží, květinová a dřevitá vůně. Jako nektar z překrásných květin, lehce mizící v dáli a přesto stále velmi přítomný.',
  `price` = 2150.00,
  `variant` = 'parfémová voda 30 ml',
  `data` = JSON_MERGE_PATCH(COALESCE(`data`, JSON_OBJECT()), CAST('{"catalog_source":{"shop":"FAnn parfumerie","url":"https://www.fann.cz/produkty/lady-million/2605/18993","product_id":2605,"variant_id":18993,"ean":"3349668612611","checked_at":"2026-09-21"},"brand":"Rabanne","variant_label":"parfémová voda 30 ml","availability_at_check":"InStock","selection_attributes":{"category":["vůně"],"product_type":["parfémová voda"],"fragrance_character":["svěží","květinová","ovocná","dřevitá","sladká"],"fragrance_notes":["neroli, citrón, malina","jasmín, pomerančový květ, gardénie","pačuli, med"],"concentration":["parfémová voda"]},"diagnostic_questions":["Pro koho vůni vybíráte a jaké vůně běžně používá?","Má být spíše svěží, květinová, sladká, dřevitá, nebo kořeněná?","Je vůně na každý den, večer, konkrétní období, nebo jako dárek?","Jak výraznou vůni a jaký rozpočet preferujete?"]}' AS JSON)),
  `published` = 1,
  `deleted` = 0
WHERE `franchise_code` = 'fun' AND `sku` = 'FUN-P020';

UPDATE `product` SET
  `description` = 'Ikonický Huile Podigieuse® Multifunkční suchý olej se 7 vzácnými 100% botanickými oleji včetně arganového a makadamiového a nenapodobitelnou texturou a ikonickou vůní pomerančového květu, vanilky a magnolie, vyživuje, hydratuje a zkrášluje pokožku tváře i těla a vlasy v jediném kroku. Navíc obsahuje 25 % omega 3, 6 a 9 mastných kyselin, které posilují kožní bariéru a pleť tak chrání.',
  `price` = 820.00,
  `variant` = 'multifunkční suchý olej pro pleť, tělo a vlasy 50 ml',
  `data` = JSON_MERGE_PATCH(COALESCE(`data`, JSON_OBJECT()), CAST('{"catalog_source":{"shop":"FAnn parfumerie","url":"https://www.fann.cz/produkty/huile-prodigieuser-multifunkcni-suchy-olej/11374/22255","product_id":11374,"variant_id":22255,"ean":"3264680009761","checked_at":"2026-09-21"},"brand":"Nuxe","variant_label":"multifunkční suchý olej pro pleť, tělo a vlasy 50 ml","availability_at_check":"InStock","selection_attributes":{"category":["péče o pleť"],"product_type":["multifunkční suchý olej pro pleť, tělo a vlasy"],"needs":["hydratace","výživa"],"features":["veganské složení","přírodní původ"],"key_ingredients":["kyselina hyaluronová"]},"diagnostic_questions":["Jaký je typ pleti a je pleť citlivá?","Jaký hlavní problém má produkt řešit?","Jakou texturu a krok rutiny hledáte?","Jsou nějaké složky nebo parfemace, kterým se chcete vyhnout?"]}' AS JSON)),
  `published` = 1,
  `deleted` = 0
WHERE `franchise_code` = 'fun' AND `sku` = 'FUN-P021';

UPDATE `product` SET
  `description` = 'Značka Lancôme představuje renovaci ikonického séra Advanced Génifique. Objevte sílu svojí pleti.',
  `price` = 2840.00,
  `variant` = 'pleťové sérum 30 ml',
  `data` = JSON_MERGE_PATCH(COALESCE(`data`, JSON_OBJECT()), CAST('{"catalog_source":{"shop":"FAnn parfumerie","url":"https://www.fann.cz/produkty/advanced-genifique/7030/13489","product_id":7030,"variant_id":13489,"ean":"3614272623545","checked_at":"2026-09-21"},"brand":"Lancôme","variant_label":"pleťové sérum 30 ml","availability_at_check":"InStock","selection_attributes":{"category":["péče o pleť"],"product_type":["pleťové sérum"],"needs":["hydratace","regenerace","rozjasnění"],"finish_and_effect":["zářivý"]},"diagnostic_questions":["Jaký je typ pleti a je pleť citlivá?","Jaký hlavní problém má produkt řešit?","Jakou texturu a krok rutiny hledáte?","Jsou nějaké složky nebo parfemace, kterým se chcete vyhnout?"]}' AS JSON)),
  `published` = 1,
  `deleted` = 0
WHERE `franchise_code` = 'fun' AND `sku` = 'FUN-P025';

UPDATE `product` SET
  `description` = 'Oblíbená řasenka Catchy Eyes s projmutým kartáčkem pro perfektní natočení a efekt kočičích očí přichází nově ve své zcela původní verzi, ale s prestižní skandinávskou známkou Allergy Certified, která dokládá, že riziko vzniku alergické reakce je zcela minimální. A to je v obzvlášť v oblasti očí přesně to, co řada z nás marně hledá!',
  `price` = 329.00,
  `variant` = 'řasenka pro citlivé oči 8 ml',
  `data` = JSON_MERGE_PATCH(COALESCE(`data`, JSON_OBJECT()), CAST('{"catalog_source":{"shop":"FAnn parfumerie","url":"https://www.fann.cz/produkty/catchy-eyes-mascara-allergy-certified-extreme-black/8273/15735","product_id":8273,"variant_id":15735,"ean":"5711914175245","checked_at":"2026-09-21"},"brand":"GOSH COPENHAGEN","variant_label":"řasenka pro citlivé oči 8 ml","availability_at_check":"InStock","selection_attributes":{"category":["líčení"],"product_type":["řasenka pro citlivé oči"],"target_audience":["citlivá pleť nebo oči","nositelé kontaktních čoček"],"needs":["objem řas","prodloužení řas","natočení řas"],"finish_and_effect":["dlouhotrvající"],"features":["bez parfemace","Allergy Certified","veganské složení"],"fragrance_character":["intenzivní"]},"diagnostic_questions":["Jaký konkrétní efekt, krytí nebo odstín hledáte?","Má být výsledek matný, saténový, přirozený, nebo zářivý?","Potřebujete voděodolnost či celodenní výdrž?","Máte citlivé oči, pleť nebo jiné omezení?"]}' AS JSON)),
  `published` = 1,
  `deleted` = 0
WHERE `franchise_code` = 'fun' AND `sku` = 'FUN-P027';

INSERT INTO `product`
  (`franchise_code`, `sku`, `name`, `description`, `price`, `stock_quantity`, `published`, `kind`, `variant`, `data`)
VALUES
  ('fun', 'FANN-8809937360834', 'Biodance Bio-Collagen Real Deep Mask', 'Biodance - Bio-Collagen Real Deep Mask – hydrogelová pleťová maska. Maska je rozdělena na dvě části (horní a dolní polovina obličeje) a je určena k nočnímu použití, případně k aplikaci po dobu alespoň 3–4 hodin pro intenzivní hydrataci a zvýšení elasticity pleti.', 120.00, 0, 1, 'skincare', 'zpevňující kolagenová maska 1 ks', CAST('{"catalog_source":{"shop":"FAnn parfumerie","url":"https://www.fann.cz/produkty/bio-collagen-real-deep-mask/12026/23377","product_id":12026,"variant_id":23377,"ean":"8809937360834","checked_at":"2026-09-21"},"brand":"Biodance","variant_label":"zpevňující kolagenová maska 1 ks","availability_at_check":"InStock","selection_attributes":{"category":["péče o pleť"],"product_type":["zpevňující kolagenová maska"],"needs":["hydratace","zklidnění","regenerace","vrásky a jemné linky","elasticita a zpevnění"],"fragrance_character":["intenzivní"],"key_ingredients":["kyselina hyaluronová","kolagen"]},"diagnostic_questions":["Jaký je typ pleti a je pleť citlivá?","Jaký hlavní problém má produkt řešit?","Jakou texturu a krok rutiny hledáte?","Jsou nějaké složky nebo parfemace, kterým se chcete vyhnout?"]}' AS JSON)),
  ('fun', 'FANN-8809624723119', 'Round Lab Birch Juice Moisturizing Mask', 'Round Lab - Birch Juice Moisturizing Mask – plátýnková maska určená k péči o pleť obličeje. Její složení zahrnuje šťávu z japonské břízy a hyaluronát sodný, které hloubkově hydratují suchou pleť.', 72.00, 0, 1, 'skincare', 'hydratační maska s březovou šťávou 1 ks', CAST('{"catalog_source":{"shop":"FAnn parfumerie","url":"https://www.fann.cz/produkty/birch-juice-moisturizing-mask/12037/23388","product_id":12037,"variant_id":23388,"ean":"8809624723119","checked_at":"2026-09-21"},"brand":"Round Lab","variant_label":"hydratační maska s březovou šťávou 1 ks","availability_at_check":"InStock","selection_attributes":{"category":["péče o pleť"],"product_type":["hydratační maska s březovou šťávou"],"target_audience":["citlivá pleť nebo oči"],"needs":["hydratace","zklidnění","regenerace"],"fragrance_character":["svěží"],"key_ingredients":["kyselina hyaluronová"]},"diagnostic_questions":["Jaký je typ pleti a je pleť citlivá?","Jaký hlavní problém má produkt řešit?","Jakou texturu a krok rutiny hledáte?","Jsou nějaké složky nebo parfemace, kterým se chcete vyhnout?"]}' AS JSON)),
  ('fun', 'FANN-8809581454743', 'Missha Airy Fit Sheet Mask Aloe', 'Hydratační plátýnková maska s obsahem aloe vera pro zklidnění podrážděné pleti. Jemná struktura masky perfektně přilne k pleti a zajistí účinné vstřebání aktivních složek.', 44.00, 0, 1, 'skincare', 'plátýnková maska 19 g', CAST('{"catalog_source":{"shop":"FAnn parfumerie","url":"https://www.fann.cz/produkty/airy-fit-sheet-mask-aloe/12159/23635","product_id":12159,"variant_id":23635,"ean":"8809581454743","checked_at":"2026-09-21"},"brand":"Missha","variant_label":"plátýnková maska 19 g","availability_at_check":"InStock","selection_attributes":{"category":["péče o pleť"],"product_type":["plátýnková maska"],"needs":["hydratace","zklidnění"],"fragrance_character":["jemná"],"key_ingredients":["aloe vera"]},"diagnostic_questions":["Jaký je typ pleti a je pleť citlivá?","Jaký hlavní problém má produkt řešit?","Jakou texturu a krok rutiny hledáte?","Jsou nějaké složky nebo parfemace, kterým se chcete vyhnout?"]}' AS JSON)),
  ('fun', 'FANN-8809581454781', 'Missha Airy Fit Sheet Mask Pearl', 'Plátýnková maska s rozjasňujícím a hydratačním účinkem. Obsahuje extrakt z perel pro rozjasnění pleti.', 44.00, 0, 1, 'skincare', 'plátýnková maska 19 g', CAST('{"catalog_source":{"shop":"FAnn parfumerie","url":"https://www.fann.cz/produkty/airy-fit-sheet-mask-pearl/12155/23631","product_id":12155,"variant_id":23631,"ean":"8809581454781","checked_at":"2026-09-21"},"brand":"Missha","variant_label":"plátýnková maska 19 g","availability_at_check":"InStock","selection_attributes":{"category":["péče o pleť"],"product_type":["plátýnková maska"],"needs":["hydratace","rozjasnění"],"finish_and_effect":["zářivý"]},"diagnostic_questions":["Jaký je typ pleti a je pleť citlivá?","Jaký hlavní problém má produkt řešit?","Jakou texturu a krok rutiny hledáte?","Jsou nějaké složky nebo parfemace, kterým se chcete vyhnout?"]}' AS JSON)),
  ('fun', 'FANN-8809581454798', 'Missha Airy Fit Sheet Mask Shea Butter', 'Výživná plátýnková maska s bambuckým máslem poskytuje suché pleti intenzivní pocit hydratace a komfortu. Jemná celulózová tkanina dokonale přiléhá k pokožce a napomáhá rovnoměrnému vstřebání pečujících složek.', 44.00, 0, 1, 'skincare', 'plátýnková maska 19 g', CAST('{"catalog_source":{"shop":"FAnn parfumerie","url":"https://www.fann.cz/produkty/airy-fit-sheet-mask-shea-butter/12156/23632","product_id":12156,"variant_id":23632,"ean":"8809581454798","checked_at":"2026-09-21"},"brand":"Missha","variant_label":"plátýnková maska 19 g","availability_at_check":"InStock","selection_attributes":{"category":["péče o pleť"],"product_type":["plátýnková maska"],"target_audience":["suchá až velmi suchá pokožka"],"needs":["hydratace","výživa","zklidnění"],"fragrance_character":["intenzivní","jemná"],"key_ingredients":["bambucké máslo"]},"diagnostic_questions":["Jaký je typ pleti a je pleť citlivá?","Jaký hlavní problém má produkt řešit?","Jakou texturu a krok rutiny hledáte?","Jsou nějaké složky nebo parfemace, kterým se chcete vyhnout?"]}' AS JSON)),
  ('fun', 'FANN-8809581454750', 'Missha Airy Fit Sheet Mask Tea Tree', 'Zklidňující pleťová maska s obsahem tea tree pomáhá zjemnit podrážděnou pleť a obnovit její rovnováhu. Lehká struktura masky výborně přilne k pleti a podporuje účinné vstřebávání aktivních složek.', 44.00, 0, 1, 'skincare', 'plátýnková maska 19 g', CAST('{"catalog_source":{"shop":"FAnn parfumerie","url":"https://www.fann.cz/produkty/airy-fit-sheet-mask-tea-tree/12157/23633","product_id":12157,"variant_id":23633,"ean":"8809581454750","checked_at":"2026-09-21"},"brand":"Missha","variant_label":"plátýnková maska 19 g","availability_at_check":"InStock","selection_attributes":{"category":["péče o pleť"],"product_type":["plátýnková maska"],"target_audience":["citlivá pleť nebo oči"],"needs":["zklidnění","regenerace"],"fragrance_character":["svěží"],"key_ingredients":["tea tree"]},"diagnostic_questions":["Jaký je typ pleti a je pleť citlivá?","Jaký hlavní problém má produkt řešit?","Jakou texturu a krok rutiny hledáte?","Jsou nějaké složky nebo parfemace, kterým se chcete vyhnout?"]}' AS JSON)),
  ('fun', 'FANN-3346470615557', 'Guerlain Abeille Royale Lotion', 'Posilující pleťová voda Fortifying Lotion z řady Abeille Royale má ve svém složení 25x vyšší obsah mateří kašičky* a díky systému mikrokapslí pomáhá pleti odolávat různým stresovým faktorům a znečištění, které viditelně ovlivňují její kvalitu a krásu.Složení je určeno pro všechny typy pleti, dokonce i pro citlivou, Obnovuje pleť tak, aby znovu získala svou optimální rovnováhu, hydrataci, pružnost a zářivost.Den po dni je kožní bariéra více posílena, pleť je odolnější a chráněná před projevy stárnutí. Tento účinn…', 2270.00, 0, 1, 'skincare', 'přípravné lotion 150 ml', CAST('{"catalog_source":{"shop":"FAnn parfumerie","url":"https://www.fann.cz/produkty/abeille-royale-lotion/7566/14444","product_id":7566,"variant_id":14444,"ean":"3346470615557","checked_at":"2026-09-21"},"brand":"Guerlain","variant_label":"přípravné lotion 150 ml","availability_at_check":"InStock","selection_attributes":{"category":["péče o pleť"],"product_type":["přípravné lotion"],"target_audience":["citlivá pleť nebo oči"],"needs":["hydratace","regenerace","elasticita a zpevnění","rozjasnění"],"finish_and_effect":["zářivý"],"features":["přírodní původ"],"fragrance_character":["svěží"],"key_ingredients":["mateří kašička"]},"diagnostic_questions":["Jaký je typ pleti a je pleť citlivá?","Jaký hlavní problém má produkt řešit?","Jakou texturu a krok rutiny hledáte?","Jsou nějaké složky nebo parfemace, kterým se chcete vyhnout?"]}' AS JSON)),
  ('fun', 'FANN-3346470615366', 'Guerlain Abeille Royale Multi-Wrinkle Minimizer Eye Cream', 'Oční krém Eye Cream Abeille Royale od Guerlain je vyvinutý specificky na vrásky v očním okolí, od jemných povrchových linek až po hlubší mimické vějířkové vrásky a den po dni pleť viditelně omlazuje. Tento oční krém obsahuje 93 % složek přírodního původu*.', 2920.00, 0, 1, 'skincare', 'oční krém 15 ml', CAST('{"catalog_source":{"shop":"FAnn parfumerie","url":"https://www.fann.cz/produkty/abeille-royale-multi-wrinkle-minimizer-eye-cream/7691/14714","product_id":7691,"variant_id":14714,"ean":"3346470615366","checked_at":"2026-09-21"},"brand":"Guerlain","variant_label":"oční krém 15 ml","availability_at_check":"InStock","selection_attributes":{"category":["péče o pleť"],"product_type":["oční krém"],"needs":["hydratace","výživa","regenerace","vrásky a jemné linky","rozjasnění"],"finish_and_effect":["zářivý"],"features":["přírodní původ"],"key_ingredients":["kyselina hyaluronová","mateří kašička","med"]},"diagnostic_questions":["Jaký je typ pleti a je pleť citlivá?","Jaký hlavní problém má produkt řešit?","Jakou texturu a krok rutiny hledáte?","Jsou nějaké složky nebo parfemace, kterým se chcete vyhnout?"]}' AS JSON)),
  ('fun', 'FANN-8011003997008', 'Versace Versense', 'Versense je perfektním propojením svěžesti a smyslnosti. Vůně sama je opojnou oslavou svěžesti inspirovanou silou přírodních živlů a je určená svůdné ženě připravené v životě okusit a vyzkoušet téměř vše.', 2280.00, 0, 1, 'fragrance', 'toaletní voda 30 ml', CAST('{"catalog_source":{"shop":"FAnn parfumerie","url":"https://www.fann.cz/produkty/versense/2565/20594","product_id":2565,"variant_id":20594,"ean":"8011003997008","checked_at":"2026-09-21"},"brand":"Versace","variant_label":"toaletní voda 30 ml","availability_at_check":"InStock","selection_attributes":{"category":["vůně"],"product_type":["toaletní voda"],"fragrance_character":["svěží","citrusová","květinová","kořeněná"],"fragrance_notes":["bergamot, zelená mandarinka, plody opuncie","jasmín, kardamom, květ líru","jasmín, kardamom, květ líru"],"concentration":["toaletní voda"]},"diagnostic_questions":["Pro koho vůni vybíráte a jaké vůně běžně používá?","Má být spíše svěží, květinová, sladká, dřevitá, nebo kořeněná?","Je vůně na každý den, večer, konkrétní období, nebo jako dárek?","Jak výraznou vůni a jaký rozpočet preferujete?"]}' AS JSON)),
  ('fun', 'FANN-850049716307', 'Michael Kors Pour Femme', 'Michael Kors Pour Femme je květinově-dřevitě-pižmová vůně, která vás zahalí do luxusu, sebevědomí a smaslnosti. Jako bohatý zlatý řetěz rozpálený sluncem prohřátou kůží, vyzařuje sofistikovanost, krásu a sílu prostřednictvím svých mnohovrstevných vonných tónů a výjimečně vytrvalé vonné stopy.', 1870.00, 0, 1, 'fragrance', 'parfémová voda 30 ml', CAST('{"catalog_source":{"shop":"FAnn parfumerie","url":"https://www.fann.cz/produkty/pour-femme/10844/22537","product_id":10844,"variant_id":22537,"ean":"850049716307","checked_at":"2026-09-21"},"brand":"Michael Kors","variant_label":"parfémová voda 30 ml","availability_at_check":"InStock","selection_attributes":{"category":["vůně"],"product_type":["parfémová voda"],"target_audience":["ženy"],"fragrance_character":["citrusová","květinová","ovocná","dřevitá","sladká","kořeněná","pižmová"],"fragrance_notes":["mandarinka, růžový pepř, černý rybíz","jasmín, růžové květy","krémová vanilka, pižmo, pačuli"],"concentration":["parfémová voda"]},"diagnostic_questions":["Pro koho vůni vybíráte a jaké vůně běžně používá?","Má být spíše svěží, květinová, sladká, dřevitá, nebo kořeněná?","Je vůně na každý den, večer, konkrétní období, nebo jako dárek?","Jak výraznou vůni a jaký rozpočet preferujete?"]}' AS JSON)),
  ('fun', 'FANN-6290171074205', 'Zimaya Sharaf Blend', 'Zimaya Sharaf Blend je bohatá orientální vůně, která ztělesňuje smyslnost a eleganci prostřednictvím mistrovské směsi kořenitých, dřevitých a sladkých tónů. Tato unisex vůně je intenzivní a tajemná, což ji činí ideální volbou pro ty, kteří vyhledávají výrazné a dlouhotrvající aroma s exotickým nádechem.', 799.00, 0, 1, 'fragrance', 'parfémový extrakt 100 ml', CAST('{"catalog_source":{"shop":"FAnn parfumerie","url":"https://www.fann.cz/produkty/sharaf-blend/11092/21701","product_id":11092,"variant_id":21701,"ean":"6290171074205","checked_at":"2026-09-21"},"brand":"Zimaya","variant_label":"parfémový extrakt 100 ml","availability_at_check":"InStock","selection_attributes":{"category":["vůně"],"product_type":["parfémový extrakt"],"target_audience":["unisex"],"finish_and_effect":["dlouhotrvající"],"fragrance_character":["květinová","dřevitá","orientální","sladká","kořeněná","ambrová","intenzivní","jemná"],"fragrance_notes":["koření, šafrán","růže, kadidlo","dřevité tóny, vanilka, ambra"],"concentration":["parfémový extrakt"]},"diagnostic_questions":["Pro koho vůni vybíráte a jaké vůně běžně používá?","Má být spíše svěží, květinová, sladká, dřevitá, nebo kořeněná?","Je vůně na každý den, večer, konkrétní období, nebo jako dárek?","Jak výraznou vůni a jaký rozpočet preferujete?"]}' AS JSON)),
  ('fun', 'FANN-6290362346531', 'Lattafa Yara Elixir', 'Lattafa Yara Elixir je svůdná a elegantní orientálně-gurmánská vůně pro ženy, která otevírá chuťově sladkou a šťavnatou kompozici jahod a černého rybízu, jež přecházejí do květinově-smyslného srdce a zakončují se teplým, vanilkovo-karamelovým základem. Ideální pro večerní události, romantické chvíle nebo jako výrazná dámská podpisová vůně.', 869.00, 0, 1, 'fragrance', 'parfémová voda 100 ml', CAST('{"catalog_source":{"shop":"FAnn parfumerie","url":"https://www.fann.cz/produkty/yara-elixir/12111/23566","product_id":12111,"variant_id":23566,"ean":"6290362346531","checked_at":"2026-09-21"},"brand":"Lattafa","variant_label":"parfémová voda 100 ml","availability_at_check":"InStock","selection_attributes":{"category":["vůně"],"product_type":["parfémová voda"],"target_audience":["ženy"],"fragrance_character":["květinová","ovocná","orientální","gurmánská","sladká","pižmová","ambrová","intenzivní"],"occasion":["večer","romantická příležitost"],"fragrance_notes":["jahoda, černý rybíz","jasmín, pomerančový květ","vanilka, karamel, ambra, pižmo"],"concentration":["parfémová voda"]},"diagnostic_questions":["Pro koho vůni vybíráte a jaké vůně běžně používá?","Má být spíše svěží, květinová, sladká, dřevitá, nebo kořeněná?","Je vůně na každý den, večer, konkrétní období, nebo jako dárek?","Jak výraznou vůni a jaký rozpočet preferujete?"]}' AS JSON)),
  ('fun', 'FANN-6290171077459', 'Afnan 9 PM Night Out Extrait de Parfum', 'Afnan 9PM Night Out je vyjádřením sebevědomí. Vůně stvořená pro nezapomenutelné noci.', 1295.00, 0, 1, 'fragrance', 'parfémový extrakt 100 ml', CAST('{"catalog_source":{"shop":"FAnn parfumerie","url":"https://www.fann.cz/produkty/9-pm-night-out-extrait-de-parfum/12110/23565","product_id":12110,"variant_id":23565,"ean":"6290171077459","checked_at":"2026-09-21"},"brand":"Afnan","variant_label":"parfémový extrakt 100 ml","availability_at_check":"InStock","selection_attributes":{"category":["vůně"],"product_type":["parfémový extrakt"],"fragrance_character":["svěží","citrusová","ovocná","dřevitá","gurmánská","sladká","kořeněná","intenzivní"],"occasion":["večer"],"fragrance_notes":["dračí ovoce, bergamot, koňak, levandule, jablko","kardamom, mahónie, semiš, karamel, cedr","fazolka tonka, dřevo akigala, ambrofix, pačuli"],"concentration":["parfémový extrakt"]},"diagnostic_questions":["Pro koho vůni vybíráte a jaké vůně běžně používá?","Má být spíše svěží, květinová, sladká, dřevitá, nebo kořeněná?","Je vůně na každý den, večer, konkrétní období, nebo jako dárek?","Jak výraznou vůni a jaký rozpočet preferujete?"]}' AS JSON)),
  ('fun', 'FANN-6290360598925', 'Lattafa Dalal', 'Lattafa Dalal je jemná, zářivá a elegantní ovocně-květinová vůně, která dokonale propojuje šťavnaté ovocné prvky s bohatým květinovým srdcem a krémově-smyslným základem. ideální pro každodenní nošení, ale i pro romantické či společenské situace.', 849.00, 0, 1, 'fragrance', 'parfémová voda 100 ml', CAST('{"catalog_source":{"shop":"FAnn parfumerie","url":"https://www.fann.cz/produkty/dalal/12113/23568","product_id":12113,"variant_id":23568,"ean":"6290360598925","checked_at":"2026-09-21"},"brand":"Lattafa","variant_label":"parfémová voda 100 ml","availability_at_check":"InStock","selection_attributes":{"category":["vůně"],"product_type":["parfémová voda"],"needs":["rozjasnění"],"finish_and_effect":["zářivý"],"fragrance_character":["citrusová","květinová","ovocná","sladká","pižmová","jemná"],"occasion":["každodenní použití","romantická příležitost","společenská příležitost"],"fragrance_notes":["jablko Golden Delicious, mandarinka","ylang-ylang, jasmín, pomerančový květ","vanilka, pižmo, dubový mech"],"concentration":["parfémová voda"]},"diagnostic_questions":["Pro koho vůni vybíráte a jaké vůně běžně používá?","Má být spíše svěží, květinová, sladká, dřevitá, nebo kořeněná?","Je vůně na každý den, večer, konkrétní období, nebo jako dárek?","Jak výraznou vůni a jaký rozpočet preferujete?"]}' AS JSON)),
  ('fun', 'FANN-6290362346548', 'Lattafa Asad Elixir', 'Lattaf Asad Elixir je intenzivní orientálně-dřevitá vůně pro muže, který vyzařuje sílu, charisma a sebevědomí. Kompozice propojuje energické kořeněné tóny s bohatým tabákovým srdcem a teplým ambrovým základem pro elegantní a dlouhotrvající stopu.', 869.00, 0, 1, 'fragrance', 'parfémová voda 100 ml', CAST('{"catalog_source":{"shop":"FAnn parfumerie","url":"https://www.fann.cz/produkty/asad-elixir/12112/23567","product_id":12112,"variant_id":23567,"ean":"6290362346548","checked_at":"2026-09-21"},"brand":"Lattafa","variant_label":"parfémová voda 100 ml","availability_at_check":"InStock","selection_attributes":{"category":["vůně"],"product_type":["parfémová voda"],"target_audience":["muži"],"finish_and_effect":["dlouhotrvající"],"fragrance_character":["citrusová","dřevitá","orientální","sladká","kořeněná","ambrová","intenzivní"],"occasion":["večer","chladnější období"],"fragrance_notes":["růžový pepř, šafrán, grep","tabák, cedr, vanilka","pačuli, olibanum (kadidlo), kašmeran, suchá ambra"],"concentration":["parfémová voda"]},"diagnostic_questions":["Pro koho vůni vybíráte a jaké vůně běžně používá?","Má být spíše svěží, květinová, sladká, dřevitá, nebo kořeněná?","Je vůně na každý den, večer, konkrétní období, nebo jako dárek?","Jak výraznou vůni a jaký rozpočet preferujete?"]}' AS JSON)),
  ('fun', 'FANN-3616307208536', 'Hugo Boss Bottled Beyond For Her', 'Ponořte se do povznášející energie s BOSS Bottled Beyond Eau de Parfum for Her – vůní spojující pivoňku a javorový sirup. Tato neodolatelná kompozice se otevírá rozkvetlou směsí pivoněk, která zachycuje zářivost a krásu této květiny.', 2080.00, 0, 1, 'fragrance', 'parfémová voda 30 ml', CAST('{"catalog_source":{"shop":"FAnn parfumerie","url":"https://www.fann.cz/produkty/bottled-beyond-for-her/12487/24389","product_id":12487,"variant_id":24389,"ean":"3616307208536","checked_at":"2026-09-21"},"brand":"Hugo Boss","variant_label":"parfémová voda 30 ml","availability_at_check":"InStock","selection_attributes":{"category":["vůně"],"product_type":["parfémová voda"],"target_audience":["ženy"],"needs":["rozjasnění"],"finish_and_effect":["zářivý"],"fragrance_character":["květinová","gurmánská","sladká","ambrová"],"fragrance_notes":["směs pivoňky, javorový sirup","směs pivoňky, javorový sirup","směs pivoňky, javorový sirup"],"concentration":["parfémová voda"]},"diagnostic_questions":["Pro koho vůni vybíráte a jaké vůně běžně používá?","Má být spíše svěží, květinová, sladká, dřevitá, nebo kořeněná?","Je vůně na každý den, večer, konkrétní období, nebo jako dárek?","Jak výraznou vůni a jaký rozpočet preferujete?"]}' AS JSON)),
  ('fun', 'FANN-5711914172794', 'GOSH COPENHAGEN Just Click It! Volume Mascara', 'NA JEDEN KLIK Nový přírůstek do rodiny Gosh řasenek je tím nejvíc „instafriendly" kouskem. Na jedno kliknutí řasenku otevřete a během několika vteřin dodáte svým řasám objem i délku.', 329.00, 0, 1, 'makeup', 'objemová řasenka 10 ml', CAST('{"catalog_source":{"shop":"FAnn parfumerie","url":"https://www.fann.cz/produkty/just-click-it-volume-mascara/8034/15299","product_id":8034,"variant_id":15299,"ean":"5711914172794","checked_at":"2026-09-21"},"brand":"GOSH COPENHAGEN","variant_label":"objemová řasenka 10 ml","availability_at_check":"InStock","selection_attributes":{"category":["líčení"],"product_type":["objemová řasenka"],"target_audience":["citlivá pleť nebo oči","nositelé kontaktních čoček"],"needs":["odlíčení a čištění","objem řas"],"features":["bez parfemace","Allergy Certified","veganské složení"]},"diagnostic_questions":["Jaký konkrétní efekt, krytí nebo odstín hledáte?","Má být výsledek matný, saténový, přirozený, nebo zářivý?","Potřebujete voděodolnost či celodenní výdrž?","Máte citlivé oči, pleť nebo jiné omezení?"]}' AS JSON)),
  ('fun', 'FANN-7618900910010', 'Mavala Minicolor', 'Barevné laky na nehty Mini Color´s jsou vyrobeny z pečlivě vybraných ingrediencí. Jsou složené z odlišných druhů pryskyřice, rozpouštědel a barevných pigmentů, obratně umožňující jednoduchou aplikaci a perfektní přilnavost.', 190.00, 0, 1, 'makeup', 'lak na nehty 5 ml', CAST('{"catalog_source":{"shop":"FAnn parfumerie","url":"https://www.fann.cz/produkty/minicolor/699/4168","product_id":699,"variant_id":4168,"ean":"7618900910010","checked_at":"2026-09-21"},"brand":"Mavala","variant_label":"lak na nehty 5 ml","availability_at_check":"InStock","selection_attributes":{"category":["líčení"],"product_type":["lak na nehty"]},"diagnostic_questions":["Jaký konkrétní efekt, krytí nebo odstín hledáte?","Má být výsledek matný, saténový, přirozený, nebo zářivý?","Potřebujete voděodolnost či celodenní výdrž?","Máte citlivé oči, pleť nebo jiné omezení?"]}' AS JSON)),
  ('fun', 'FANN-5711914205775', 'GOSH COPENHAGEN Forever Mineral Eyeshadow Waterproof', 'Krémové stíny v sytých metalických barvách, které drží po celý den! Ne, tohle není sen, ale jde o vylepšenou verzi původních oblíbených stínů Forever Eye Shadows.', 329.00, 0, 1, 'makeup', 'minerální voděodolné stíny v tužce 1,4 g', CAST('{"catalog_source":{"shop":"FAnn parfumerie","url":"https://www.fann.cz/produkty/forever-mineral-eyeshadow-waterproof/11742/22985","product_id":11742,"variant_id":22985,"ean":"5711914205775","checked_at":"2026-09-21"},"brand":"GOSH COPENHAGEN","variant_label":"minerální voděodolné stíny v tužce 1,4 g","availability_at_check":"InStock","selection_attributes":{"category":["líčení"],"product_type":["minerální voděodolné stíny v tužce"],"finish_and_effect":["metalický","vysoká pigmentace","dlouhotrvající","voděodolný"],"fragrance_character":["intenzivní"]},"diagnostic_questions":["Jaký konkrétní efekt, krytí nebo odstín hledáte?","Má být výsledek matný, saténový, přirozený, nebo zářivý?","Potřebujete voděodolnost či celodenní výdrž?","Máte citlivé oči, pleť nebo jiné omezení?"]}' AS JSON)),
  ('fun', 'FANN-5711914183882', 'GOSH COPENHAGEN Matte Eye Liner', 'PASTELKY PRO DOSPĚLÉ Doplňte si do své povinné výbavy odstíny, které jste si tajně přáli, ale báli jste po nich zeptat! Matné tužky na oči s krémovým složením lze po nanesení perfektně rozpracovat a vrstvit, jak ale zaschnou, nehnou se.', 249.00, 0, 1, 'makeup', 'matná tužka na oči 1,2 g', CAST('{"catalog_source":{"shop":"FAnn parfumerie","url":"https://www.fann.cz/produkty/matte-eye-liner/8033/17870","product_id":8033,"variant_id":17870,"ean":"5711914183882","checked_at":"2026-09-21"},"brand":"GOSH COPENHAGEN","variant_label":"matná tužka na oči 1,2 g","availability_at_check":"InStock","selection_attributes":{"category":["líčení"],"product_type":["matná tužka na oči"],"finish_and_effect":["matný","vysoká pigmentace","voděodolný"],"features":["bez parfemace","Allergy Certified"]},"diagnostic_questions":["Jaký konkrétní efekt, krytí nebo odstín hledáte?","Má být výsledek matný, saténový, přirozený, nebo zářivý?","Potřebujete voděodolnost či celodenní výdrž?","Máte citlivé oči, pleť nebo jiné omezení?"]}' AS JSON)),
  ('fun', 'FANN-3346470432116', 'Guerlain Mad Eyes', 'Řasenka MAD EYES od Guerlain poskytuje řasám nebývalé rozlišení a objem: +112 %* objemu v jediném okamžiku. Řasy jsou hustší, delší a krásně natočené po dobu 24 hodin**.', 1150.00, 0, 1, 'makeup', 'řasenka pro objem a zahuštění řas', CAST('{"catalog_source":{"shop":"FAnn parfumerie","url":"https://www.fann.cz/produkty/mad-eyes/7567/14445","product_id":7567,"variant_id":14445,"ean":"3346470432116","checked_at":"2026-09-21"},"brand":"Guerlain","variant_label":"řasenka pro objem a zahuštění řas","availability_at_check":"InStock","selection_attributes":{"category":["líčení"],"product_type":["řasenka pro objem a zahuštění řas"],"needs":["objem řas","prodloužení řas"],"finish_and_effect":["přirozený","dlouhotrvající","voděodolný"],"fragrance_character":["intenzivní"]},"diagnostic_questions":["Jaký konkrétní efekt, krytí nebo odstín hledáte?","Má být výsledek matný, saténový, přirozený, nebo zářivý?","Potřebujete voděodolnost či celodenní výdrž?","Máte citlivé oči, pleť nebo jiné omezení?"]}' AS JSON)),
  ('fun', 'FANN-3346470431621', 'Guerlain Terracotta Compact Matte Powder', 'Sluncem políbená pleť, která působí přirozeným opáleným a zdravým dojmem. Speciální složení zanechá pleť krásně zmatněnou.', 1670.00, 0, 1, 'makeup', 'matující pudr 10 g', CAST('{"catalog_source":{"shop":"FAnn parfumerie","url":"https://www.fann.cz/produkty/terracotta-compact-matte-powder/7686/14695","product_id":7686,"variant_id":14695,"ean":"3346470431621","checked_at":"2026-09-21"},"brand":"Guerlain","variant_label":"matující pudr 10 g","availability_at_check":"InStock","selection_attributes":{"category":["líčení"],"product_type":["matující pudr"],"finish_and_effect":["matný","přirozený"]},"diagnostic_questions":["Jaký konkrétní efekt, krytí nebo odstín hledáte?","Má být výsledek matný, saténový, přirozený, nebo zářivý?","Potřebujete voděodolnost či celodenní výdrž?","Máte citlivé oči, pleť nebo jiné omezení?"]}' AS JSON)),
  ('fun', 'FANN-3346470417175', 'Guerlain KissKiss', '"Rtěnka KissKiss je dokonalou kombinací barvy a lesku a nabízí intenzivní saténový povrch s dokonalou odolností. KissKiss má jemnou, krémovou a návykovou texturu a intenzivní, rozjasňující a zářivou barvu.', 1210.00, 0, 1, 'makeup', 'krémová saténová rtěnka 3,5 g', CAST('{"catalog_source":{"shop":"FAnn parfumerie","url":"https://www.fann.cz/produkty/kisskiss/10407/20015","product_id":10407,"variant_id":20015,"ean":"3346470417175","checked_at":"2026-09-21"},"brand":"Guerlain","variant_label":"krémová saténová rtěnka 3,5 g","availability_at_check":"InStock","selection_attributes":{"category":["líčení"],"product_type":["krémová saténová rtěnka"],"needs":["hydratace","elasticita a zpevnění","rozjasnění"],"finish_and_effect":["saténový","zářivý","dlouhotrvající"],"fragrance_character":["svěží","intenzivní"]},"diagnostic_questions":["Jaký konkrétní efekt, krytí nebo odstín hledáte?","Má být výsledek matný, saténový, přirozený, nebo zářivý?","Potřebujete voděodolnost či celodenní výdrž?","Máte citlivé oči, pleť nebo jiné omezení?"]}' AS JSON)),
  ('fun', 'FANN-6412600848502', 'Lumene CC Color Correcting Cream SPF20', 'Bright future ahead for skin caring make-up. CC Color Correcting Cream je lehký fluidní make-up se středním krytím, který redukuje zarudnutí a zdokonaluje pleť pro sjednocený a přirozeně zářivý vzhled.', 499.00, 0, 1, 'makeup', 'tónovaný pleťový CC krém 30 ml', CAST('{"catalog_source":{"shop":"FAnn parfumerie","url":"https://www.fann.cz/produkty/cc-color-correcting-cream-spf20/11744/23000","product_id":11744,"variant_id":23000,"ean":"6412600848502","checked_at":"2026-09-21"},"brand":"Lumene","variant_label":"tónovaný pleťový CC krém 30 ml","availability_at_check":"InStock","selection_attributes":{"category":["líčení"],"product_type":["tónovaný pleťový CC krém"],"needs":["hydratace","výživa","rozjasnění","odlíčení a čištění","redukce zarudnutí","sjednocení tónu pleti"],"finish_and_effect":["přirozený","zářivý","střední krytí"],"features":["veganské složení","SPF"]},"diagnostic_questions":["Jaký konkrétní efekt, krytí nebo odstín hledáte?","Má být výsledek matný, saténový, přirozený, nebo zářivý?","Potřebujete voděodolnost či celodenní výdrž?","Máte citlivé oči, pleť nebo jiné omezení?"]}' AS JSON)),
  ('fun', 'FANN-711221983866', 'Salt & Stone Natural Deodorant Extra Strength Neroli & Basil', 'Konečně deodorant pro všechny, kteří žijí svůj život v neustálém pohybu a pro svoji pokožku chtějí jen to nejlepší z přírodních zdrojů. Značka Salt & Stone vytvořila silný přírodní deodorant formulovaný pro 24 hodinovou ochranu.', 540.00, 0, 1, 'bodycare', 'přírodní deodorant s extra účinkem 75 g', CAST('{"catalog_source":{"shop":"FAnn parfumerie","url":"https://www.fann.cz/produkty/natural-deodorant-extra-strength-neroli-basil/10403/19994","product_id":10403,"variant_id":19994,"ean":"711221983866","checked_at":"2026-09-21"},"brand":"Salt & Stone","variant_label":"přírodní deodorant s extra účinkem 75 g","availability_at_check":"InStock","selection_attributes":{"category":["péče o tělo"],"product_type":["přírodní deodorant s extra účinkem"],"needs":["hydratace","zklidnění","regenerace","ochrana proti pocení a zápachu"],"finish_and_effect":["dlouhotrvající"],"features":["bez hliníku","přírodní původ"],"fragrance_character":["svěží","květinová","sladká"],"key_ingredients":["kyselina hyaluronová","probiotika"]},"diagnostic_questions":["Jakou potřebu pokožky nebo typ ochrany řešíte?","Je pokožka suchá či citlivá?","Preferujete parfemaci, přírodní složení nebo některé složky vynechat?","Je produkt pro běžné použití, cestování, nebo jako dárek?"]}' AS JSON)),
  ('fun', 'FANN-711221984337', 'Salt & Stone Mini Deo Set', 'Hvězda mezi deodoranty, miláček internetu Objevte sadu čtyř oceňovaných vůní deodorantů kultovní kalifornské značky SALT & STONE – perfektní způsob, jak s nimi začít, ideální dárek nebo cestovní verze rituálu, který již znáte a už nechcete jiný! Sada obsahuje čtyři deodoranty v cestovní velikosti ve variantách: Santal & Vetiver Bergamot & Hinoki Neroli & Basil Black Rose & Oud Deodoranty SALT & STONE mají přírodní složení plné pečujících látek spolu s originálními vůněmi.', 1090.00, 0, 1, 'bodycare', 'set mini deodorantů', CAST('{"catalog_source":{"shop":"FAnn parfumerie","url":"https://www.fann.cz/produkty/mini-deo-set/11992/23337","product_id":11992,"variant_id":23337,"ean":"711221984337","checked_at":"2026-09-21"},"brand":"Salt & Stone","variant_label":"set mini deodorantů","availability_at_check":"InStock","selection_attributes":{"category":["péče o tělo"],"product_type":["set mini deodorantů"],"needs":["ochrana proti pocení a zápachu"],"features":["dárková sada","cestovní balení"],"fragrance_character":["citrusová","dřevitá"],"occasion":["dárek"],"key_ingredients":["kyselina hyaluronová","probiotika"]},"diagnostic_questions":["Jakou potřebu pokožky nebo typ ochrany řešíte?","Je pokožka suchá či citlivá?","Preferujete parfemaci, přírodní složení nebo některé složky vynechat?","Je produkt pro běžné použití, cestování, nebo jako dárek?"]}' AS JSON)),
  ('fun', 'FANN-4013162018512', 'Fenjal Intensive Body Milk', 'Tělové mléko Fenjal Intensive dodová pokožce chybějící hydrataci a výživu. Právě díky získané vlhkosti zůstane pokožka dlouhodobě příjemně uvolněná a přirozeně pružná.', 180.00, 0, 1, 'bodycare', 'tělové mléko 200 ml', CAST('{"catalog_source":{"shop":"FAnn parfumerie","url":"https://www.fann.cz/produkty/intensive-body-milk/2038/5601","product_id":2038,"variant_id":5601,"ean":"4013162018512","checked_at":"2026-09-21"},"brand":"Fenjal","variant_label":"tělové mléko 200 ml","availability_at_check":"InStock","selection_attributes":{"category":["péče o tělo"],"product_type":["tělové mléko"],"target_audience":["suchá až velmi suchá pokožka"],"needs":["hydratace","výživa","zklidnění","regenerace","elasticita a zpevnění"],"finish_and_effect":["přirozený"],"key_ingredients":["bambucké máslo","avokádový olej"]},"diagnostic_questions":["Jakou potřebu pokožky nebo typ ochrany řešíte?","Je pokožka suchá či citlivá?","Preferujete parfemaci, přírodní složení nebo některé složky vynechat?","Je produkt pro běžné použití, cestování, nebo jako dárek?"]}' AS JSON)),
  ('fun', 'FANN-711221983880', 'Salt & Stone Natural Deodorant Extra Strength Bergamot & Hinoki', 'Konečně deodorant pro všechny, kteří žijí svůj život v neustálém pohybu a pro svoji pokožku chtějí jen to nejlepší z přírodních zdrojů. Značka Salt & Stone vytvořila silný přírodní deodorant formulovaný pro 24 hodinovou ochranu.', 540.00, 0, 1, 'bodycare', 'přírodní deodorant s extra účinkem 75 g', CAST('{"catalog_source":{"shop":"FAnn parfumerie","url":"https://www.fann.cz/produkty/natural-deodorant-extra-strength-bergamot-hinoki/10421/20045","product_id":10421,"variant_id":20045,"ean":"711221983880","checked_at":"2026-09-21"},"brand":"Salt & Stone","variant_label":"přírodní deodorant s extra účinkem 75 g","availability_at_check":"InStock","selection_attributes":{"category":["péče o tělo"],"product_type":["přírodní deodorant s extra účinkem"],"needs":["hydratace","zklidnění","regenerace","ochrana proti pocení a zápachu"],"finish_and_effect":["dlouhotrvající"],"features":["bez hliníku","přírodní původ"],"fragrance_character":["svěží","citrusová"],"key_ingredients":["kyselina hyaluronová","probiotika"]},"diagnostic_questions":["Jakou potřebu pokožky nebo typ ochrany řešíte?","Je pokožka suchá či citlivá?","Preferujete parfemaci, přírodní složení nebo některé složky vynechat?","Je produkt pro běžné použití, cestování, nebo jako dárek?"]}' AS JSON)),
  ('fun', 'FANN-4013162025473', 'Fenjal Intensive Shower Cream', 'Sprchový krém Intensive dodává pokožce potřebnou hydrataci a výživu. Šetrně čistí pokožku a celého těla a zbavuje ji nečistot.', 150.00, 0, 1, 'bodycare', 'sprchový krém 200 ml', CAST('{"catalog_source":{"shop":"FAnn parfumerie","url":"https://www.fann.cz/produkty/intensive-shower-cream/5315/9770","product_id":5315,"variant_id":9770,"ean":"4013162025473","checked_at":"2026-09-21"},"brand":"Fenjal","variant_label":"sprchový krém 200 ml","availability_at_check":"InStock","selection_attributes":{"category":["péče o tělo"],"product_type":["sprchový krém"],"needs":["hydratace","zklidnění","regenerace","elasticita a zpevnění","odlíčení a čištění"],"fragrance_character":["jemná"],"occasion":["každodenní použití"],"key_ingredients":["bambucké máslo","avokádový olej"]},"diagnostic_questions":["Jakou potřebu pokožky nebo typ ochrany řešíte?","Je pokožka suchá či citlivá?","Preferujete parfemaci, přírodní složení nebo některé složky vynechat?","Je produkt pro běžné použití, cestování, nebo jako dárek?"]}' AS JSON)),
  ('fun', 'FANN-8699954700450', 'Pielor Immortal Patern Hand Cream', 'Hydratační krém na ruce Pielor z kolekce Immortal Pattern intenzivně vyživuje a hydratuje pokožku. Obsahuje 5 % bambuckého másla a je obohacena o Vitamín A.', 69.00, 0, 1, 'bodycare', 'hydratační krém na ruce 30ml', CAST('{"catalog_source":{"shop":"FAnn parfumerie","url":"https://www.fann.cz/produkty/immortal-patern-hand-cream/5526/10155","product_id":5526,"variant_id":10155,"ean":"8699954700450","checked_at":"2026-09-21"},"brand":"Pielor","variant_label":"hydratační krém na ruce 30ml","availability_at_check":"InStock","selection_attributes":{"category":["péče o tělo"],"product_type":["hydratační krém na ruce"],"needs":["hydratace","výživa","regenerace"],"finish_and_effect":["bez lepivého pocitu"],"features":["SPF"],"fragrance_character":["intenzivní"],"key_ingredients":["bambucké máslo"]},"diagnostic_questions":["Jakou potřebu pokožky nebo typ ochrany řešíte?","Je pokožka suchá či citlivá?","Preferujete parfemaci, přírodní složení nebo některé složky vynechat?","Je produkt pro běžné použití, cestování, nebo jako dárek?"]}' AS JSON))
ON DUPLICATE KEY UPDATE
  `name` = VALUES(`name`), `description` = VALUES(`description`), `price` = VALUES(`price`),
  `published` = 1, `kind` = VALUES(`kind`), `variant` = VALUES(`variant`),
  `data` = VALUES(`data`), `deleted` = 0;

INSERT IGNORE INTO `product_category` (`product_id`, `category_id`)
SELECT p.`id`, c.`id` FROM `product` p JOIN `category` c
  ON c.`franchise_code` = 'fun' AND c.`syscode` = CASE p.`kind`
    WHEN 'fragrance' THEN 'perfumes' WHEN 'makeup' THEN 'makeup'
    WHEN 'skincare' THEN 'creams-and-care' WHEN 'bodycare' THEN 'creams-and-care' ELSE 'other' END
WHERE p.`franchise_code` = 'fun' AND p.`sku` LIKE 'FANN-%' AND p.`deleted` = 0;

COMMIT;

SELECT COUNT(*) AS enriched_fann_products FROM `product` WHERE `franchise_code` = 'fun' AND JSON_UNQUOTE(JSON_EXTRACT(`data`, '$.catalog_source.shop')) = 'FAnn parfumerie' AND `deleted` = 0;
