-- Idempotent discovery rules; migration does not run any synchronization.
INSERT INTO etymolog_sync_job (franchise_code,title,provider,language,kind,batch_size,interval_seconds,enabled) SELECT 'etymolog','Český Wikislovník – příjmení','wiktionary-cs','cs','surname',3,300,1 WHERE NOT EXISTS (SELECT 1 FROM etymolog_sync_job WHERE franchise_code='etymolog' AND provider='wiktionary-cs' AND language='cs' AND kind='surname');
INSERT INTO etymolog_sync_job (franchise_code,title,provider,language,kind,batch_size,interval_seconds,enabled) SELECT 'etymolog','Český Wikislovník – rodná jména','wiktionary-cs','cs','given',3,300,1 WHERE NOT EXISTS (SELECT 1 FROM etymolog_sync_job WHERE franchise_code='etymolog' AND provider='wiktionary-cs' AND language='cs' AND kind='given');
INSERT INTO etymolog_sync_job (franchise_code,title,provider,language,kind,batch_size,interval_seconds,enabled) SELECT 'etymolog','Český Wikislovník – přednostní příjmení','wiktionary-cs','cs','surname_priority',3,300,1 WHERE NOT EXISTS (SELECT 1 FROM etymolog_sync_job WHERE franchise_code='etymolog' AND provider='wiktionary-cs' AND language='cs' AND kind='surname_priority');
INSERT INTO etymolog_sync_job (franchise_code,title,provider,language,kind,batch_size,interval_seconds,enabled) SELECT 'etymolog','Český Wikislovník – přednostní rodná jména','wiktionary-cs','cs','given_priority',3,300,1 WHERE NOT EXISTS (SELECT 1 FROM etymolog_sync_job WHERE franchise_code='etymolog' AND provider='wiktionary-cs' AND language='cs' AND kind='given_priority');
INSERT INTO etymolog_sync_job (franchise_code,title,provider,language,kind,batch_size,interval_seconds,enabled) SELECT 'etymolog','Anglický Wiktionary – přednostní česká příjmení','wiktionary','cs','surname_priority',3,300,1 WHERE NOT EXISTS (SELECT 1 FROM etymolog_sync_job WHERE franchise_code='etymolog' AND provider='wiktionary' AND language='cs' AND kind='surname_priority');
INSERT INTO etymolog_sync_job (franchise_code,title,provider,language,kind,batch_size,interval_seconds,enabled) SELECT 'etymolog','Anglický Wiktionary – přednostní česká rodná jména','wiktionary','cs','given_priority',3,300,1 WHERE NOT EXISTS (SELECT 1 FROM etymolog_sync_job WHERE franchise_code='etymolog' AND provider='wiktionary' AND language='cs' AND kind='given_priority');
INSERT INTO etymolog_sync_job (franchise_code,title,provider,language,kind,batch_size,interval_seconds,enabled) SELECT 'etymolog','Francouzský Wiktionnaire – příjmení','wiktionary-fr','cs','surname',3,300,1 WHERE NOT EXISTS (SELECT 1 FROM etymolog_sync_job WHERE franchise_code='etymolog' AND provider='wiktionary-fr' AND language='cs' AND kind='surname');
INSERT INTO etymolog_sync_job (franchise_code,title,provider,language,kind,batch_size,interval_seconds,enabled) SELECT 'etymolog','Francouzský Wiktionnaire – rodná jména','wiktionary-fr','cs','given',3,300,1 WHERE NOT EXISTS (SELECT 1 FROM etymolog_sync_job WHERE franchise_code='etymolog' AND provider='wiktionary-fr' AND language='cs' AND kind='given');
INSERT INTO etymolog_sync_job (franchise_code,title,provider,language,kind,batch_size,interval_seconds,enabled) SELECT 'etymolog','Francouzský Wiktionnaire – přednostní příjmení','wiktionary-fr','cs','surname_priority',3,300,1 WHERE NOT EXISTS (SELECT 1 FROM etymolog_sync_job WHERE franchise_code='etymolog' AND provider='wiktionary-fr' AND language='cs' AND kind='surname_priority');
INSERT INTO etymolog_sync_job (franchise_code,title,provider,language,kind,batch_size,interval_seconds,enabled) SELECT 'etymolog','Francouzský Wiktionnaire – přednostní rodná jména','wiktionary-fr','cs','given_priority',3,300,1 WHERE NOT EXISTS (SELECT 1 FROM etymolog_sync_job WHERE franchise_code='etymolog' AND provider='wiktionary-fr' AND language='cs' AND kind='given_priority');
