-- Idempotent bootstrap, reference and product data for the FAnn CRM tenant.
-- Uses existing php-core tables; no schema changes.
-- Safe to rerun: existing administrator passwords are never overwritten.

SET NAMES utf8mb4;
START TRANSACTION;

INSERT INTO `role` (`franchise_code`, `name`, `label`, `position`)
VALUES
  ('fun', 'admin', 'Administrátor', 10),
  ('fun', 'manager', 'Manažer', 20),
  ('fun', 'user', 'Uživatel', 30)
ON DUPLICATE KEY UPDATE
  `label` = VALUES(`label`),
  `position` = VALUES(`position`),
  `deleted` = 0;

SET @fun_admin_role_id = (
  SELECT `id`
  FROM `role`
  WHERE `franchise_code` = 'fun'
    AND `name` = 'admin'
  LIMIT 1
);

INSERT INTO `user`
  (`franchise_code`, `first_name`, `last_name`, `email`, `password`, `role_id`, `status`)
SELECT
  'fun', 'FAnn', 'Admin', 'admin@fann.cz',
  '$2y$12$nmRE/TC4K3OYnBRaqnLfz.IGMYHjt1RVgej7139P7u7ijXz0epGWy',
  @fun_admin_role_id, 'active'
WHERE NOT EXISTS (
  SELECT 1
  FROM `user`
  WHERE `franchise_code` = 'fun'
    AND `role_id` = @fun_admin_role_id
)
ON DUPLICATE KEY UPDATE
  `id` = `id`;

UPDATE `user`
SET
  `email` = 'admin@fann.cz',
  `password` = '$2y$12$nmRE/TC4K3OYnBRaqnLfz.IGMYHjt1RVgej7139P7u7ijXz0epGWy',
  `status` = 'active',
  `deleted` = 0
WHERE `franchise_code` = 'fun'
  AND `role_id` = @fun_admin_role_id;

INSERT INTO `enumeration`
  (`franchise_code`, `type`, `syscode`, `label`, `value`, `position`, `published`, `data`)
VALUES
  ('fun', 'client_type', 'specific_fragrance', 'Jdu pro konkrétní parfém', 'Zná produkt; chce rychlost, dostupnost a jistotu.', 10, 1, CAST('{"profile_number":1,"questions":["Chcete stejnou vůni jako obvykle?","Máte preferovanou velikost?","Můžu ukázat výhodnější set nebo vyšší koncentraci?"],"typical_objections":["Chci jen tohle.","Nic dalšího nepotřebuji.","Jinde je levnější."]}' AS JSON)),
  ('fun', 'client_type', 'gift_buyer', 'Kupující dárek', 'Nezná přesně produkt; potřebuje jistotu, že se trefí.', 20, 1, CAST('{"profile_number":2,"questions":["Pro koho dárek vybíráte?","Co ten člověk používá / jaký má styl?","V jakém rozpočtu se chcete pohybovat?"],"typical_objections":["Nevím, co má rád/a.","Co když se netrefím?","Je to moc drahé."]}' AS JSON)),
  ('fun', 'client_type', 'best_price_hunter', 'Lovec nejlepší ceny', 'Porovnává ceny, akce a hodnotu nákupu.', 30, 1, CAST('{"profile_number":3,"questions":["Je pro vás rozhodující hlavně cena?","S čím naši nabídku porovnáváte?","Zajímala by vás sada nebo větší balení s lepší hodnotou?"],"typical_objections":["Na internetu je levnější.","Počkám si na slevu.","Za parfém tolik nedám."]}' AS JSON)),
  ('fun', 'client_type', 'new_fragrance_seeker', 'Hledám novou vůni', 'Rozhoduje podle pocitu; potřebuje zúžit výběr.', 40, 1, CAST('{"profile_number":4,"questions":["Jaké vůně jste používal/a doposud?","Spíš svěží, sladká, výrazná, nebo jemná?","Na každý den, nebo na speciální příležitost?"],"typical_objections":["Nevím, co chci.","Všechny už mi voní stejně.","Musím si to rozmyslet."]}' AS JSON)),
  ('fun', 'client_type', 'premium_customer', 'Prémiový zákazník', 'Chce kvalitu, originalitu, servis a pocit výjimečnosti.', 50, 1, CAST('{"profile_number":5,"questions":["Hledáte něco, co nebude mít každý?","Co je pro vás u vůně nejdůležitější?","Máte značky nebo typy vůní, ke kterým se vracíte?"],"typical_objections":["Tohle je moc běžné.","Za tu cenu čekám něco výjimečného.","Chci něco originálnějšího."]}' AS JSON)),
  ('fun', 'client_type', 'social_media_customer', 'Zákazník ze sociálních sítí', 'Přichází kvůli trendu nebo doporučení influencera.', 60, 1, CAST('{"profile_number":6,"questions":["Co vás na produktu zaujalo?","Už jste ho někdy zkusil/a na sobě?","Chcete porovnat i podobné alternativy?"],"typical_objections":["Na TikToku říkali, že je nejlepší.","Chci přesně tuhle.","Čekal/a jsem něco jiného."]}' AS JSON)),
  ('fun', 'client_type', 'indecisive_customer', 'Nerozhodný zákazník', 'Má více favoritů; potřebuje potvrdit rozhodnutí.', 70, 1, CAST('{"profile_number":7,"questions":["Co se vám na těchto variantách líbí nejvíc?","Kdy budete produkt nejčastěji používat?","Kdybyste měl/a jednu variantu vyřadit, která by to byla?"],"typical_objections":["Nemůžu se rozhodnout.","Líbí se mi obě.","Ještě si to promyslím."]}' AS JSON)),
  ('fun', 'client_type', 'cosmetics_customer', 'Kosmetický zákazník', 'Řeší konkrétní potřebu, účinek, odstín nebo typ pleti.', 80, 1, CAST('{"profile_number":8,"questions":["Jaký výsledek od produktu očekáváte?","Co používáte nyní?","Je něco, čemu se chcete vyhnout?"],"typical_objections":["Nevím, jestli mi sedne.","Mám citlivou pleť.","Je to drahé na vyzkoušení."]}' AS JSON)),
  ('fun', 'client_type', 'informed_connoisseur', 'Informovaný znalec', 'Zná značky, složení, koncentrace, výdrž a konkurenci.', 90, 1, CAST('{"profile_number":9,"questions":["Jaké složky nebo charakter preferujete?","Je důležitější výdrž, projekce, nebo kompozice?","Hledáte něco podobného, nebo úplně jiného?"],"typical_objections":["Výdrž není dostatečná.","Znám podobnou věc za méně.","Není to ničím zajímavé."]}' AS JSON)),
  ('fun', 'client_type', 'just_browsing', 'Jen se dívám', 'Nemá jasný nákupní záměr; nechce tlak.', 100, 1, CAST('{"profile_number":10,"questions":["Hledáte něco konkrétního, nebo inspiraci?","Můžu ukázat jednu zajímavou novinku?","Raději vůni, péči, nebo líčení?"],"typical_objections":["Jen se dívám.","Nic nepotřebuji.","Nechci teď nic kupovat."]}' AS JSON))
ON DUPLICATE KEY UPDATE
  `label` = VALUES(`label`),
  `value` = VALUES(`value`),
  `position` = VALUES(`position`),
  `published` = 1,
  `data` = VALUES(`data`),
  `deleted` = 0;

INSERT INTO `product`
  (`franchise_code`, `sku`, `name`, `description`, `price`, `stock_quantity`, `published`, `kind`, `data`)
VALUES
  ('fun', 'FUN-P001', 'Armani Acqua di Giò EDT', 'Osvědčená pánská klasika; snadno nositelná.', 1500.00, 0, 1, 'fragrance', CAST('{"approx_price":{"min":1500,"max":2500,"currency":"CZK"},"character":"Svěží, vodní, univerzální","purchase_probability":{"specific_fragrance":30,"gift_buyer":30,"best_price_hunter":8,"new_fragrance_seeker":30,"premium_customer":8,"social_media_customer":8,"indecisive_customer":30,"cosmetics_customer":8,"informed_connoisseur":8,"just_browsing":10},"target_segments":["specific_fragrance","gift_buyer","new_fragrance_seeker","indecisive_customer"],"main_sales_argument":"Osvědčená pánská klasika; snadno nositelná.","alternative_product_name":"Acqua di Giò Profondo","upsell_upgrade":"Vyšší koncentrace / Profondo / větší objem","basket_if_upgrade_declined":"Deodorant nebo sprchový gel; ideálně sada"}' AS JSON)),
  ('fun', 'FUN-P002', 'Armani Acqua di Giò Profondo EDP', 'Modernější, hlubší a výraznější varianta.', 1700.00, 0, 1, 'fragrance', CAST('{"approx_price":{"min":1700,"max":2800,"currency":"CZK"},"character":"Svěží, mořská, hlubší","purchase_probability":{"specific_fragrance":8,"gift_buyer":8,"best_price_hunter":8,"new_fragrance_seeker":35,"premium_customer":35,"social_media_customer":8,"indecisive_customer":8,"cosmetics_customer":8,"informed_connoisseur":35,"just_browsing":10},"target_segments":["new_fragrance_seeker","premium_customer","informed_connoisseur"],"main_sales_argument":"Modernější, hlubší a výraznější varianta.","alternative_product_name":"Acqua di Giò Parfum","upsell_upgrade":"Parfum nebo větší flakon","basket_if_upgrade_declined":"Deodorant / sprchový gel / sada"}' AS JSON)),
  ('fun', 'FUN-P003', 'Armani Acqua di Giò Parfum', 'Prémiovější a intenzivnější charakter.', 1900.00, 0, 1, 'fragrance', CAST('{"approx_price":{"min":1900,"max":3200,"currency":"CZK"},"character":"Elegantní, intenzivní","purchase_probability":{"specific_fragrance":8,"gift_buyer":8,"best_price_hunter":8,"new_fragrance_seeker":8,"premium_customer":35,"social_media_customer":8,"indecisive_customer":35,"cosmetics_customer":8,"informed_connoisseur":35,"just_browsing":10},"target_segments":["premium_customer","indecisive_customer","informed_connoisseur"],"main_sales_argument":"Prémiovější a intenzivnější charakter.","alternative_product_name":"Acqua di Giò Profondo","upsell_upgrade":"Větší flakon / prémiová edice","basket_if_upgrade_declined":"Doprovodná péče nebo dárková sada"}' AS JSON)),
  ('fun', 'FUN-P004', 'Armani Stronger With You Intensely', 'Výrazná moderní vůně, silná volba na večer.', 1600.00, 0, 1, 'fragrance', CAST('{"approx_price":{"min":1600,"max":2700,"currency":"CZK"},"character":"Sladká, hřejivá, výrazná","purchase_probability":{"specific_fragrance":8,"gift_buyer":8,"best_price_hunter":8,"new_fragrance_seeker":35,"premium_customer":8,"social_media_customer":35,"indecisive_customer":35,"cosmetics_customer":8,"informed_connoisseur":8,"just_browsing":10},"target_segments":["new_fragrance_seeker","social_media_customer","indecisive_customer"],"main_sales_argument":"Výrazná moderní vůně, silná volba na večer.","alternative_product_name":"Versace Eros","upsell_upgrade":"Vyšší koncentrace / větší objem","basket_if_upgrade_declined":"Dárkový set / deodorant"}' AS JSON)),
  ('fun', 'FUN-P005', 'Armani Code', 'Bezpečná elegantní volba; vhodná i jako dárek.', 1900.00, 0, 1, 'fragrance', CAST('{"approx_price":{"min":1900,"max":3000,"currency":"CZK"},"character":"Elegantní, smyslná","purchase_probability":{"specific_fragrance":8,"gift_buyer":35,"best_price_hunter":8,"new_fragrance_seeker":35,"premium_customer":35,"social_media_customer":8,"indecisive_customer":8,"cosmetics_customer":8,"informed_connoisseur":8,"just_browsing":10},"target_segments":["gift_buyer","new_fragrance_seeker","premium_customer"],"main_sales_argument":"Bezpečná elegantní volba; vhodná i jako dárek.","alternative_product_name":"BOSS The Scent","upsell_upgrade":"Vyšší koncentrace / větší objem","basket_if_upgrade_declined":"Sprchový gel / deodorant / sada"}' AS JSON)),
  ('fun', 'FUN-P006', 'BOSS Bottled', 'Známá pánská vůně; nízké riziko špatné volby.', 1500.00, 0, 1, 'fragrance', CAST('{"approx_price":{"min":1500,"max":2500,"currency":"CZK"},"character":"Dřevitá, univerzální","purchase_probability":{"specific_fragrance":35,"gift_buyer":35,"best_price_hunter":8,"new_fragrance_seeker":8,"premium_customer":8,"social_media_customer":8,"indecisive_customer":35,"cosmetics_customer":8,"informed_connoisseur":8,"just_browsing":10},"target_segments":["specific_fragrance","gift_buyer","indecisive_customer"],"main_sales_argument":"Známá pánská vůně; nízké riziko špatné volby.","alternative_product_name":"Armani Code","upsell_upgrade":"Větší balení / intenzivnější verze","basket_if_upgrade_declined":"Deodorant / sprchový gel"}' AS JSON)),
  ('fun', 'FUN-P007', 'BOSS The Scent', 'Atraktivnější večerní charakter.', 1700.00, 0, 1, 'fragrance', CAST('{"approx_price":{"min":1700,"max":2700,"currency":"CZK"},"character":"Smyslná, večerní","purchase_probability":{"specific_fragrance":8,"gift_buyer":35,"best_price_hunter":8,"new_fragrance_seeker":35,"premium_customer":8,"social_media_customer":8,"indecisive_customer":35,"cosmetics_customer":8,"informed_connoisseur":8,"just_browsing":10},"target_segments":["gift_buyer","new_fragrance_seeker","indecisive_customer"],"main_sales_argument":"Atraktivnější večerní charakter.","alternative_product_name":"Stronger With You","upsell_upgrade":"Vyšší koncentrace","basket_if_upgrade_declined":"Dárková sada / doprovodná péče"}' AS JSON)),
  ('fun', 'FUN-P008', 'Versace Eros', 'Výrazný charakter; silná volba pro mladší cílovku.', 1500.00, 0, 1, 'fragrance', CAST('{"approx_price":{"min":1500,"max":2500,"currency":"CZK"},"character":"Výrazná, sladší, energická","purchase_probability":{"specific_fragrance":8,"gift_buyer":8,"best_price_hunter":8,"new_fragrance_seeker":35,"premium_customer":8,"social_media_customer":35,"indecisive_customer":35,"cosmetics_customer":8,"informed_connoisseur":8,"just_browsing":10},"target_segments":["new_fragrance_seeker","social_media_customer","indecisive_customer"],"main_sales_argument":"Výrazný charakter; silná volba pro mladší cílovku.","alternative_product_name":"Stronger With You Intensely","upsell_upgrade":"Vyšší koncentrace / větší objem","basket_if_upgrade_declined":"Deodorant / sprchový gel"}' AS JSON)),
  ('fun', 'FUN-P009', 'Rabanne 1 Million', 'Velmi známá vůně; snadno rozpoznatelný dárek.', 1600.00, 0, 1, 'fragrance', CAST('{"approx_price":{"min":1600,"max":2600,"currency":"CZK"},"character":"Sladká, kořeněná, výrazná","purchase_probability":{"specific_fragrance":35,"gift_buyer":35,"best_price_hunter":8,"new_fragrance_seeker":8,"premium_customer":8,"social_media_customer":35,"indecisive_customer":8,"cosmetics_customer":8,"informed_connoisseur":8,"just_browsing":10},"target_segments":["specific_fragrance","gift_buyer","social_media_customer"],"main_sales_argument":"Velmi známá vůně; snadno rozpoznatelný dárek.","alternative_product_name":"Versace Eros","upsell_upgrade":"Parfum / větší objem","basket_if_upgrade_declined":"Dárkový set"}' AS JSON)),
  ('fun', 'FUN-P010', 'Montblanc Explorer', 'Prémiový dojem za přístupnější cenu.', 1300.00, 0, 1, 'fragrance', CAST('{"approx_price":{"min":1300,"max":2200,"currency":"CZK"},"character":"Dřevitá, moderní","purchase_probability":{"specific_fragrance":8,"gift_buyer":35,"best_price_hunter":35,"new_fragrance_seeker":35,"premium_customer":8,"social_media_customer":8,"indecisive_customer":8,"cosmetics_customer":8,"informed_connoisseur":8,"just_browsing":10},"target_segments":["gift_buyer","best_price_hunter","new_fragrance_seeker"],"main_sales_argument":"Prémiový dojem za přístupnější cenu.","alternative_product_name":"BOSS Bottled","upsell_upgrade":"Větší objem","basket_if_upgrade_declined":"Deodorant / sprchový gel"}' AS JSON)),
  ('fun', 'FUN-P011', 'Armani My Way', 'Moderní a univerzální dámská vůně.', 1700.00, 0, 1, 'fragrance', CAST('{"approx_price":{"min":1700,"max":2800,"currency":"CZK"},"character":"Květinová, ženská","purchase_probability":{"specific_fragrance":30,"gift_buyer":30,"best_price_hunter":8,"new_fragrance_seeker":30,"premium_customer":8,"social_media_customer":8,"indecisive_customer":30,"cosmetics_customer":8,"informed_connoisseur":8,"just_browsing":10},"target_segments":["specific_fragrance","gift_buyer","new_fragrance_seeker","indecisive_customer"],"main_sales_argument":"Moderní a univerzální dámská vůně.","alternative_product_name":"Lancôme Idôle","upsell_upgrade":"Intense / větší flakon","basket_if_upgrade_declined":"Tělové mléko / sada"}' AS JSON)),
  ('fun', 'FUN-P012', 'Armani Sì', 'Elegantní a bezpečná dárková volba.', 1700.00, 0, 1, 'fragrance', CAST('{"approx_price":{"min":1700,"max":2900,"currency":"CZK"},"character":"Elegantní, ženská","purchase_probability":{"specific_fragrance":35,"gift_buyer":35,"best_price_hunter":8,"new_fragrance_seeker":8,"premium_customer":35,"social_media_customer":8,"indecisive_customer":8,"cosmetics_customer":8,"informed_connoisseur":8,"just_browsing":10},"target_segments":["specific_fragrance","gift_buyer","premium_customer"],"main_sales_argument":"Elegantní a bezpečná dárková volba.","alternative_product_name":"La Vie Est Belle","upsell_upgrade":"Intense / větší flakon","basket_if_upgrade_declined":"Tělová péče / sada"}' AS JSON)),
  ('fun', 'FUN-P013', 'Armani Sì Passione', 'Výraznější a mladistvější alternativa klasického Sì.', 1700.00, 0, 1, 'fragrance', CAST('{"approx_price":{"min":1700,"max":2900,"currency":"CZK"},"character":"Ovocná, výraznější","purchase_probability":{"specific_fragrance":8,"gift_buyer":8,"best_price_hunter":8,"new_fragrance_seeker":35,"premium_customer":8,"social_media_customer":35,"indecisive_customer":35,"cosmetics_customer":8,"informed_connoisseur":8,"just_browsing":10},"target_segments":["new_fragrance_seeker","social_media_customer","indecisive_customer"],"main_sales_argument":"Výraznější a mladistvější alternativa klasického Sì.","alternative_product_name":"YSL Libre","upsell_upgrade":"Intense / větší flakon","basket_if_upgrade_declined":"Dárková sada / tělová péče"}' AS JSON)),
  ('fun', 'FUN-P014', 'Armani Acqua di Gioia', 'Lehká a univerzální vůně na den.', 1500.00, 0, 1, 'fragrance', CAST('{"approx_price":{"min":1500,"max":2500,"currency":"CZK"},"character":"Svěží, vodní","purchase_probability":{"specific_fragrance":8,"gift_buyer":35,"best_price_hunter":8,"new_fragrance_seeker":35,"premium_customer":8,"social_media_customer":8,"indecisive_customer":35,"cosmetics_customer":8,"informed_connoisseur":8,"just_browsing":10},"target_segments":["gift_buyer","new_fragrance_seeker","indecisive_customer"],"main_sales_argument":"Lehká a univerzální vůně na den.","alternative_product_name":"DKNY Be Delicious","upsell_upgrade":"Větší objem","basket_if_upgrade_declined":"Tělová péče"}' AS JSON)),
  ('fun', 'FUN-P015', 'YSL Libre', 'Luxusní moderní charakter a výrazná identita.', 2000.00, 0, 1, 'fragrance', CAST('{"approx_price":{"min":2000,"max":3500,"currency":"CZK"},"character":"Elegantní, moderní, výrazná","purchase_probability":{"specific_fragrance":8,"gift_buyer":8,"best_price_hunter":8,"new_fragrance_seeker":8,"premium_customer":30,"social_media_customer":30,"indecisive_customer":30,"cosmetics_customer":8,"informed_connoisseur":30,"just_browsing":10},"target_segments":["premium_customer","social_media_customer","indecisive_customer","informed_connoisseur"],"main_sales_argument":"Luxusní moderní charakter a výrazná identita.","alternative_product_name":"Armani Sì","upsell_upgrade":"Intense / Le Parfum / větší flakon","basket_if_upgrade_declined":"Tělové mléko / sada"}' AS JSON)),
  ('fun', 'FUN-P016', 'YSL Black Opium', 'Rozpoznatelná a výrazná večerní vůně.', 2000.00, 0, 1, 'fragrance', CAST('{"approx_price":{"min":2000,"max":3500,"currency":"CZK"},"character":"Sladká, kávová, večerní","purchase_probability":{"specific_fragrance":8,"gift_buyer":8,"best_price_hunter":8,"new_fragrance_seeker":35,"premium_customer":8,"social_media_customer":35,"indecisive_customer":35,"cosmetics_customer":8,"informed_connoisseur":8,"just_browsing":10},"target_segments":["new_fragrance_seeker","social_media_customer","indecisive_customer"],"main_sales_argument":"Rozpoznatelná a výrazná večerní vůně.","alternative_product_name":"La Vie Est Belle","upsell_upgrade":"Vyšší koncentrace / větší flakon","basket_if_upgrade_declined":"Tělové mléko / sada"}' AS JSON)),
  ('fun', 'FUN-P017', 'Lancôme La Vie Est Belle', 'Známá ženská vůně s výrazným charakterem.', 1900.00, 0, 1, 'fragrance', CAST('{"approx_price":{"min":1900,"max":3200,"currency":"CZK"},"character":"Sladká, výrazná","purchase_probability":{"specific_fragrance":30,"gift_buyer":30,"best_price_hunter":8,"new_fragrance_seeker":30,"premium_customer":8,"social_media_customer":8,"indecisive_customer":30,"cosmetics_customer":8,"informed_connoisseur":8,"just_browsing":10},"target_segments":["specific_fragrance","gift_buyer","new_fragrance_seeker","indecisive_customer"],"main_sales_argument":"Známá ženská vůně s výrazným charakterem.","alternative_product_name":"Black Opium","upsell_upgrade":"Intense / větší flakon","basket_if_upgrade_declined":"Dárková sada / tělové mléko"}' AS JSON)),
  ('fun', 'FUN-P018', 'Lancôme Idôle', 'Modernější a lehčí dámská volba.', 1800.00, 0, 1, 'fragrance', CAST('{"approx_price":{"min":1800,"max":3000,"currency":"CZK"},"character":"Čistá, květinová, moderní","purchase_probability":{"specific_fragrance":8,"gift_buyer":35,"best_price_hunter":8,"new_fragrance_seeker":35,"premium_customer":8,"social_media_customer":35,"indecisive_customer":8,"cosmetics_customer":8,"informed_connoisseur":8,"just_browsing":10},"target_segments":["gift_buyer","new_fragrance_seeker","social_media_customer"],"main_sales_argument":"Modernější a lehčí dámská volba.","alternative_product_name":"Armani My Way","upsell_upgrade":"Intense / větší flakon","basket_if_upgrade_declined":"Tělová péče / sada"}' AS JSON)),
  ('fun', 'FUN-P019', 'DKNY Be Delicious', 'Známá, svěží a cenově přístupnější.', 900.00, 0, 1, 'fragrance', CAST('{"approx_price":{"min":900,"max":2000,"currency":"CZK"},"character":"Svěží, ovocná","purchase_probability":{"specific_fragrance":30,"gift_buyer":30,"best_price_hunter":30,"new_fragrance_seeker":30,"premium_customer":8,"social_media_customer":8,"indecisive_customer":8,"cosmetics_customer":8,"informed_connoisseur":8,"just_browsing":10},"target_segments":["specific_fragrance","gift_buyer","best_price_hunter","new_fragrance_seeker"],"main_sales_argument":"Známá, svěží a cenově přístupnější.","alternative_product_name":"Acqua di Gioia","upsell_upgrade":"Větší objem","basket_if_upgrade_declined":"Tělová péče / drobný doplněk"}' AS JSON)),
  ('fun', 'FUN-P020', 'Rabanne Lady Million', 'Známý produkt; snadná dárková volba.', 1600.00, 0, 1, 'fragrance', CAST('{"approx_price":{"min":1600,"max":2700,"currency":"CZK"},"character":"Sladká, výrazná","purchase_probability":{"specific_fragrance":35,"gift_buyer":35,"best_price_hunter":8,"new_fragrance_seeker":8,"premium_customer":8,"social_media_customer":35,"indecisive_customer":8,"cosmetics_customer":8,"informed_connoisseur":8,"just_browsing":10},"target_segments":["specific_fragrance","gift_buyer","social_media_customer"],"main_sales_argument":"Známý produkt; snadná dárková volba.","alternative_product_name":"Sì Passione","upsell_upgrade":"Parfum / větší flakon","basket_if_upgrade_declined":"Dárková sada"}' AS JSON)),
  ('fun', 'FUN-P021', 'Nuxe Huile Prodigieuse', 'Jeden produkt na tělo, pleť i vlasy.', 800.00, 0, 1, 'skincare', CAST('{"approx_price":{"min":800,"max":1200,"currency":"CZK"},"character":"Multifunkční suchý olej","purchase_probability":{"specific_fragrance":8,"gift_buyer":35,"best_price_hunter":35,"new_fragrance_seeker":8,"premium_customer":8,"social_media_customer":8,"indecisive_customer":8,"cosmetics_customer":35,"informed_connoisseur":8,"just_browsing":10},"target_segments":["gift_buyer","best_price_hunter","cosmetics_customer"],"main_sales_argument":"Jeden produkt na tělo, pleť i vlasy.","alternative_product_name":"Nuxe tělová péče","upsell_upgrade":"Větší balení / prémiová varianta","basket_if_upgrade_declined":"Další Nuxe péče / dárkový set"}' AS JSON)),
  ('fun', 'FUN-P022', 'Clinique Moisture Surge', 'Jednoduchá odpověď na potřebu hydratace.', 900.00, 0, 1, 'skincare', CAST('{"approx_price":{"min":900,"max":1500,"currency":"CZK"},"character":"Intenzivní hydratace","purchase_probability":{"specific_fragrance":8,"gift_buyer":35,"best_price_hunter":8,"new_fragrance_seeker":8,"premium_customer":8,"social_media_customer":8,"indecisive_customer":8,"cosmetics_customer":35,"informed_connoisseur":8,"just_browsing":10},"target_segments":["gift_buyer","cosmetics_customer"],"main_sales_argument":"Jednoduchá odpověď na potřebu hydratace.","alternative_product_name":"Clinique hydratační řada","upsell_upgrade":"Větší balení / intenzivnější péče","basket_if_upgrade_declined":"Sérum / oční péče / cleanser"}' AS JSON)),
  ('fun', 'FUN-P023', 'Estée Lauder Advanced Night Repair', 'Ikonická prémiová péče; vhodná do vyšší rutiny.', 2000.00, 0, 1, 'skincare', CAST('{"approx_price":{"min":2000,"max":3500,"currency":"CZK"},"character":"Prémiové sérum","purchase_probability":{"specific_fragrance":8,"gift_buyer":8,"best_price_hunter":8,"new_fragrance_seeker":8,"premium_customer":35,"social_media_customer":8,"indecisive_customer":8,"cosmetics_customer":35,"informed_connoisseur":35,"just_browsing":10},"target_segments":["premium_customer","cosmetics_customer","informed_connoisseur"],"main_sales_argument":"Ikonická prémiová péče; vhodná do vyšší rutiny.","alternative_product_name":"Lancôme Génifique","upsell_upgrade":"Větší balení / prémiovější set","basket_if_upgrade_declined":"Krém + oční péče"}' AS JSON)),
  ('fun', 'FUN-P024', 'Clinique Dramatically Different', 'Jednoduchá každodenní rutina a dobrá hodnota.', 900.00, 0, 1, 'skincare', CAST('{"approx_price":{"min":900,"max":1500,"currency":"CZK"},"character":"Základní hydratační péče","purchase_probability":{"specific_fragrance":8,"gift_buyer":8,"best_price_hunter":35,"new_fragrance_seeker":8,"premium_customer":8,"social_media_customer":8,"indecisive_customer":8,"cosmetics_customer":35,"informed_connoisseur":8,"just_browsing":10},"target_segments":["best_price_hunter","cosmetics_customer"],"main_sales_argument":"Jednoduchá každodenní rutina a dobrá hodnota.","alternative_product_name":"Moisture Surge","upsell_upgrade":"Větší balení","basket_if_upgrade_declined":"Cleanser / sérum"}' AS JSON)),
  ('fun', 'FUN-P025', 'Lancôme Génifique', 'Prémiová péče zaměřená na vzhled a komfort pleti.', 2000.00, 0, 1, 'skincare', CAST('{"approx_price":{"min":2000,"max":3500,"currency":"CZK"},"character":"Prémiové sérum","purchase_probability":{"specific_fragrance":8,"gift_buyer":8,"best_price_hunter":8,"new_fragrance_seeker":8,"premium_customer":35,"social_media_customer":8,"indecisive_customer":8,"cosmetics_customer":35,"informed_connoisseur":35,"just_browsing":10},"target_segments":["premium_customer","cosmetics_customer","informed_connoisseur"],"main_sales_argument":"Prémiová péče zaměřená na vzhled a komfort pleti.","alternative_product_name":"Advanced Night Repair","upsell_upgrade":"Větší balení / set","basket_if_upgrade_declined":"Denní nebo noční krém / oční péče"}' AS JSON)),
  ('fun', 'FUN-P026', 'Clinique Take The Day Off', 'Praktický produkt každodenní rutiny.', 700.00, 0, 1, 'skincare', CAST('{"approx_price":{"min":700,"max":1100,"currency":"CZK"},"character":"Odličování","purchase_probability":{"specific_fragrance":8,"gift_buyer":8,"best_price_hunter":35,"new_fragrance_seeker":8,"premium_customer":8,"social_media_customer":8,"indecisive_customer":8,"cosmetics_customer":35,"informed_connoisseur":8,"just_browsing":10},"target_segments":["best_price_hunter","cosmetics_customer"],"main_sales_argument":"Praktický produkt každodenní rutiny.","alternative_product_name":"Jiný odličovač Clinique","upsell_upgrade":"Větší balení","basket_if_upgrade_declined":"Čisticí gel + krém"}' AS JSON)),
  ('fun', 'FUN-P027', 'GOSH Catchy Eyes Mascara', 'Dostupný produkt; nízká bariéra vyzkoušení.', 200.00, 0, 1, 'makeup', CAST('{"approx_price":{"min":200,"max":400,"currency":"CZK"},"character":"Řasenka, každodenní líčení","purchase_probability":{"specific_fragrance":8,"gift_buyer":8,"best_price_hunter":35,"new_fragrance_seeker":8,"premium_customer":8,"social_media_customer":8,"indecisive_customer":8,"cosmetics_customer":35,"informed_connoisseur":8,"just_browsing":10},"target_segments":["best_price_hunter","cosmetics_customer"],"main_sales_argument":"Dostupný produkt; nízká bariéra vyzkoušení.","alternative_product_name":"Jiná GOSH řasenka","upsell_upgrade":"Prémiovější řasenka","basket_if_upgrade_declined":"Linka / odličovač"}' AS JSON)),
  ('fun', 'FUN-P028', 'Estée Lauder Double Wear', 'Výdrž a prémiové krytí.', 1200.00, 0, 1, 'makeup', CAST('{"approx_price":{"min":1200,"max":1700,"currency":"CZK"},"character":"Dlouhotrvající make-up","purchase_probability":{"specific_fragrance":8,"gift_buyer":8,"best_price_hunter":8,"new_fragrance_seeker":8,"premium_customer":35,"social_media_customer":8,"indecisive_customer":8,"cosmetics_customer":35,"informed_connoisseur":35,"just_browsing":10},"target_segments":["premium_customer","cosmetics_customer","informed_connoisseur"],"main_sales_argument":"Výdrž a prémiové krytí.","alternative_product_name":"Lancôme make-up","upsell_upgrade":"Větší/prestižnější varianta dle nabídky","basket_if_upgrade_declined":"Primer / pudr / odličovač"}' AS JSON)),
  ('fun', 'FUN-P029', 'Clinique High Impact Mascara', 'Prémiovější každodenní řasenka.', 700.00, 0, 1, 'makeup', CAST('{"approx_price":{"min":700,"max":1000,"currency":"CZK"},"character":"Univerzální řasenka","purchase_probability":{"specific_fragrance":8,"gift_buyer":35,"best_price_hunter":8,"new_fragrance_seeker":8,"premium_customer":8,"social_media_customer":8,"indecisive_customer":8,"cosmetics_customer":35,"informed_connoisseur":8,"just_browsing":10},"target_segments":["gift_buyer","cosmetics_customer"],"main_sales_argument":"Prémiovější každodenní řasenka.","alternative_product_name":"GOSH Catchy Eyes","upsell_upgrade":"Prémiová/objemová varianta","basket_if_upgrade_declined":"Odličovač / linka"}' AS JSON)),
  ('fun', 'FUN-P030', 'Nuxe Rêve de Miel', 'Dostupný doplněk a vhodný drobný dárek.', 300.00, 0, 1, 'skincare', CAST('{"approx_price":{"min":300,"max":800,"currency":"CZK"},"character":"Výživná péče","purchase_probability":{"specific_fragrance":8,"gift_buyer":35,"best_price_hunter":35,"new_fragrance_seeker":8,"premium_customer":8,"social_media_customer":8,"indecisive_customer":8,"cosmetics_customer":35,"informed_connoisseur":8,"just_browsing":10},"target_segments":["gift_buyer","best_price_hunter","cosmetics_customer"],"main_sales_argument":"Dostupný doplněk a vhodný drobný dárek.","alternative_product_name":"Huile Prodigieuse","upsell_upgrade":"Větší balení / dárková sada","basket_if_upgrade_declined":"Kombinace více Nuxe produktů"}' AS JSON))
ON DUPLICATE KEY UPDATE
  `name` = VALUES(`name`),
  `description` = VALUES(`description`),
  `price` = VALUES(`price`),
  `published` = 1,
  `kind` = VALUES(`kind`),
  `data` = VALUES(`data`),
  `deleted` = 0;

COMMIT;

SELECT
  (SELECT COUNT(*) FROM `role` WHERE `franchise_code` = 'fun' AND `deleted` = 0) AS fun_roles,
  (SELECT COUNT(*) FROM `user` u JOIN `role` r ON r.`id` = u.`role_id` WHERE u.`franchise_code` = 'fun' AND r.`name` = 'admin' AND u.`deleted` = 0 AND u.`status` = 'active') AS fun_active_admins,
  (SELECT COUNT(*) FROM `enumeration` WHERE `franchise_code` = 'fun' AND `type` = 'client_type' AND `deleted` = 0) AS fun_profiles,
  (SELECT COUNT(*) FROM `product` WHERE `franchise_code` = 'fun' AND `sku` LIKE 'FUN-P%' AND `deleted` = 0) AS fun_products,
  (SELECT COUNT(*) FROM `product` WHERE `franchise_code` = 'fun' AND `sku` LIKE 'FUN-P%' AND JSON_LENGTH(JSON_EXTRACT(`data`, '$.purchase_probability')) = 10) AS products_with_10_probabilities;
