-- TRAM mode dictionary; endpoints and credentials stay in transport-configure.php.
SET NAMES utf8mb4;
START TRANSACTION;
INSERT INTO enumeration(franchise_code,type,syscode,label,value,position,published) SELECT 'tram','transport_mode','bus','Autobus','bus',1,1 WHERE NOT EXISTS (SELECT 1 FROM enumeration WHERE franchise_code='tram' AND type='transport_mode' AND syscode='bus');
INSERT INTO enumeration(franchise_code,type,syscode,label,value,position,published) SELECT 'tram','transport_mode','tram','Tramvaj','tram',2,1 WHERE NOT EXISTS (SELECT 1 FROM enumeration WHERE franchise_code='tram' AND type='transport_mode' AND syscode='tram');
INSERT INTO enumeration(franchise_code,type,syscode,label,value,position,published) SELECT 'tram','transport_mode','train','Vlak','train',3,1 WHERE NOT EXISTS (SELECT 1 FROM enumeration WHERE franchise_code='tram' AND type='transport_mode' AND syscode='train');
INSERT INTO enumeration(franchise_code,type,syscode,label,value,position,published) SELECT 'tram','transport_mode','metro','Metro','metro',4,1 WHERE NOT EXISTS (SELECT 1 FROM enumeration WHERE franchise_code='tram' AND type='transport_mode' AND syscode='metro');
INSERT INTO enumeration(franchise_code,type,syscode,label,value,position,published) SELECT 'tram','transport_mode','trolleybus','Trolejbus','trolleybus',5,1 WHERE NOT EXISTS (SELECT 1 FROM enumeration WHERE franchise_code='tram' AND type='transport_mode' AND syscode='trolleybus');
INSERT INTO enumeration(franchise_code,type,syscode,label,value,position,published) SELECT 'tram','transport_mode','ferry','Trajekt','ferry',6,1 WHERE NOT EXISTS (SELECT 1 FROM enumeration WHERE franchise_code='tram' AND type='transport_mode' AND syscode='ferry');
INSERT INTO enumeration(franchise_code,type,syscode,label,value,position,published) SELECT 'tram','transport_mode','coach','Dálkový autobus','coach',7,1 WHERE NOT EXISTS (SELECT 1 FROM enumeration WHERE franchise_code='tram' AND type='transport_mode' AND syscode='coach');
INSERT INTO enumeration(franchise_code,type,syscode,label,value,position,published) SELECT 'tram','transport_mode','airplane','Letadlo','airplane',8,1 WHERE NOT EXISTS (SELECT 1 FROM enumeration WHERE franchise_code='tram' AND type='transport_mode' AND syscode='airplane');
INSERT INTO enumeration(franchise_code,type,syscode,label,value,position,published) SELECT 'tram','transport_mode','cable_car','Pozemní lanová dráha','cable_car',9,1 WHERE NOT EXISTS (SELECT 1 FROM enumeration WHERE franchise_code='tram' AND type='transport_mode' AND syscode='cable_car');
INSERT INTO enumeration(franchise_code,type,syscode,label,value,position,published) SELECT 'tram','transport_mode','gondola','Visutá lanová dráha','gondola',10,1 WHERE NOT EXISTS (SELECT 1 FROM enumeration WHERE franchise_code='tram' AND type='transport_mode' AND syscode='gondola');
INSERT INTO enumeration(franchise_code,type,syscode,label,value,position,published) SELECT 'tram','transport_mode','funicular','Lanovka','funicular',11,1 WHERE NOT EXISTS (SELECT 1 FROM enumeration WHERE franchise_code='tram' AND type='transport_mode' AND syscode='funicular');
INSERT INTO enumeration(franchise_code,type,syscode,label,value,position,published) SELECT 'tram','transport_mode','monorail','Jednokolejka','monorail',12,1 WHERE NOT EXISTS (SELECT 1 FROM enumeration WHERE franchise_code='tram' AND type='transport_mode' AND syscode='monorail');
COMMIT;
